#!/usr/bin/env python3
"""Regenerate Yilin Press (译林版) junior high school English dictionary JSON files."""

import json, os

DICTS_DIR = os.path.join(os.path.dirname(__file__), '..', 'public', 'dicts')

GRADE_7_UPPER = [
    {"name": "e-dog", "trans": ["电子狗"]}, {"name": "master", "trans": ["主人；大师"]},
    {"name": "grade", "trans": ["年级"]}, {"name": "student", "trans": ["学生"]},
    {"name": "reading", "trans": ["阅读"]}, {"name": "classmate", "trans": ["同班同学"]},
    {"name": "classroom", "trans": ["教室"]}, {"name": "after school", "trans": ["放学后"]},
    {"name": "after class", "trans": ["下课后"]}, {"name": "slim", "trans": ["苗条的"]},
    {"name": "be good at", "trans": ["擅长于"]}, {"name": "over", "trans": ["穿过；在……之上"]},
    {"name": "age", "trans": ["年龄"]}, {"name": "looks", "trans": ["相貌，容貌"]},
    {"name": "cute", "trans": ["可爱的；讨人喜欢的"]}, {"name": "hobby", "trans": ["业余爱好"]},
    {"name": "glad", "trans": ["高兴的"]}, {"name": "everyone", "trans": ["每人，人人"]},
    {"name": "come from", "trans": ["来自"]}, {"name": "glasses", "trans": ["（复）眼镜"]},
    {"name": "dancing", "trans": ["跳舞，舞蹈"]}, {"name": "swimming", "trans": ["游泳"]},
    {"name": "walking", "trans": ["散步，步行"]}, {"name": "really", "trans": ["的确，确实"]},
    {"name": "bowl", "trans": ["碗，盆"]}, {"name": "time", "trans": ["次，回"]},
    {"name": "tennis", "trans": ["网球"]}, {"name": "volleyball", "trans": ["排球"]},
    {"name": "table tennis", "trans": ["乒乓球"]}, {"name": "player", "trans": ["运动员"]},
    {"name": "enjoy", "trans": ["享受；欣赏；喜爱"]}, {"name": "member", "trans": ["成员"]},
    {"name": "club", "trans": ["俱乐部"]}, {"name": "free", "trans": ["空闲的"]},
    {"name": "hope", "trans": ["希望"]}, {"name": "dream", "trans": ["梦想；梦"]},
    {"name": "true", "trans": ["真的，真实的"]}, {"name": "come true", "trans": ["变为现实"]},
    {"name": "drawing", "trans": ["画画"]}, {"name": "weekend", "trans": ["周末"]},
    {"name": "of course", "trans": ["当然"]}, {"name": "shop", "trans": ["购物"]},
    {"name": "else", "trans": ["另外；其他"]}, {"name": "a lot of / lots of", "trans": ["许多；大量"]},
    {"name": "fun", "trans": ["享乐，乐趣；有趣的事"]}, {"name": "team", "trans": ["队；组"]},
    {"name": "talk about/of", "trans": ["谈论"]}, {"name": "match", "trans": ["比赛，竞赛"]},
    {"name": "hero", "trans": ["偶像；英雄"]}, {"name": "which", "trans": ["哪一个"]},
    {"name": "best", "trans": ["最，最好地"]}, {"name": "so", "trans": ["因此；如此；非常"]},
    {"name": "biology", "trans": ["生物"]}, {"name": "geography", "trans": ["地理"]},
    {"name": "history", "trans": ["历史"]}, {"name": "date", "trans": ["日期"]},
    {"name": "meeting", "trans": ["会议；集会"]}, {"name": "o'clock", "trans": ["（表示整点）点钟"]},
    {"name": "gate", "trans": ["大门"]}, {"name": "show sb. around", "trans": ["领某人参观"]},
    {"name": "around", "trans": ["到处，向各处"]}, {"name": "show", "trans": ["引，带，领"]},
    {"name": "front", "trans": ["前面"]}, {"name": "in front of", "trans": ["在……前面"]},
    {"name": "building", "trans": ["建筑物，房子，楼房"]}, {"name": "ground", "trans": ["地，地面"]},
    {"name": "ground floor", "trans": ["（英）一楼"]}, {"name": "bright", "trans": ["明亮的"]},
    {"name": "modern", "trans": ["现代的，新式的"]}, {"name": "hall", "trans": ["礼堂，大厅"]},
    {"name": "diary", "trans": ["日记"]}, {"name": "look at", "trans": ["看一看"]},
    {"name": "wall", "trans": ["墙"]}, {"name": "let me see", "trans": ["让我想想"]},
    {"name": "pardon", "trans": ["什么，请再说一遍"]}, {"name": "phone", "trans": ["电话"]},
    {"name": "from...to...", "trans": ["从……到……"]}, {"name": "take", "trans": ["需要……时间，费时"]},
    {"name": "get up", "trans": ["起床"]}, {"name": "go to school", "trans": ["去上学"]},
    {"name": "a.m.", "trans": ["上午"]}, {"name": "p.m.", "trans": ["下午"]},
    {"name": "only", "trans": ["只，仅"]}, {"name": "sure", "trans": ["当然"]},
    {"name": "kind", "trans": ["种类"]}, {"name": "all kinds of", "trans": ["各种各样的"]},
    {"name": "borrow", "trans": ["借，借用"]}, {"name": "letter", "trans": ["信，函"]},
    {"name": "few", "trans": ["不多（的），少数（的）"]}, {"name": "a few", "trans": ["一些，少量"]},
    {"name": "away", "trans": ["离开，远离"]}, {"name": "far away", "trans": ["远离"]},
    {"name": "on foot", "trans": ["走路，步行"]}, {"name": "all the best", "trans": ["一切顺利，万事如意"]},
    {"name": "wake", "trans": ["醒，唤醒"]}, {"name": "wake up", "trans": ["醒来"]},
    {"name": "shall", "trans": ["（表示提出或征求意见）"]}, {"name": "hill", "trans": ["小山"]},
    {"name": "seldom", "trans": ["很少，不常"]}, {"name": "out", "trans": ["出来，向外，外出"]},
    {"name": "go out", "trans": ["出去"]}, {"name": "need", "trans": ["需要"]},
    {"name": "rest", "trans": ["休息，歇息"]}, {"name": "just", "trans": ["只是"]},
    {"name": "have fun", "trans": ["玩得高兴"]}, {"name": "have lessons", "trans": ["上课"]},
    {"name": "after-school", "trans": ["课后的"]}, {"name": "activity", "trans": ["活动"]},
    {"name": "homework", "trans": ["家庭作业"]}, {"name": "go to bed", "trans": ["去睡觉"]},
    {"name": "usually", "trans": ["通常，经常"]}, {"name": "never", "trans": ["从不，绝不"]},
    {"name": "be late for", "trans": ["迟到"]}, {"name": "start", "trans": ["开始，着手"]},
    {"name": "quarter", "trans": ["一刻钟"]}, {"name": "past", "trans": ["晚于"]},
    {"name": "in the morning", "trans": ["在上午"]}, {"name": "first", "trans": ["首先"]},
    {"name": "chat", "trans": ["聊天，闲聊"]}, {"name": "each", "trans": ["每人，每个，每件"]},
    {"name": "other", "trans": ["另外，其他"]}, {"name": "each other", "trans": ["互相"]},
    {"name": "practice", "trans": ["练习，训练"]}, {"name": "have a good time", "trans": ["过得愉快"]},
    {"name": "wish", "trans": ["希望，祝愿"]}, {"name": "would", "trans": ["（表示客气地建议或邀请）"]},
    {"name": "life", "trans": ["生活，生命"]}, {"name": "roller skating", "trans": ["溜旱冰"]},
    {"name": "luck", "trans": ["好运，幸运"]}, {"name": "museum", "trans": ["博物馆"]},
    {"name": "once", "trans": ["一次"]}, {"name": "twice", "trans": ["两次"]},
    {"name": "picnic", "trans": ["野餐"]}, {"name": "dislike", "trans": ["不喜爱，厌恶"]},
    {"name": "reason", "trans": ["原因，理由"]}, {"name": "ready", "trans": ["准备好，准备完毕"]},
    {"name": "learn", "trans": ["学，学习，学会"]}, {"name": "world", "trans": ["世界"]},
    {"name": "celebrate", "trans": ["庆祝，庆贺"]}, {"name": "guess", "trans": ["猜，猜测"]},
    {"name": "dress", "trans": ["穿着，穿衣"]}, {"name": "dress up", "trans": ["乔装打扮"]},
    {"name": "as", "trans": ["作为，当作"]}, {"name": "ghost", "trans": ["鬼，鬼魂"]},
    {"name": "Christmas", "trans": ["圣诞节"]}, {"name": "festival", "trans": ["节日"]},
    {"name": "because", "trans": ["因为"]}, {"name": "present", "trans": ["礼物"]},
    {"name": "together", "trans": ["在一起，共同"]}, {"name": "moon cake", "trans": ["月饼"]},
    {"name": "full", "trans": ["满的"]}, {"name": "USA", "trans": ["美国"]},
    {"name": "mask", "trans": ["面具，面罩"]}, {"name": "paint", "trans": ["用颜料涂"]},
    {"name": "pumpkin", "trans": ["南瓜"]}, {"name": "lantern", "trans": ["灯笼，提灯"]},
    {"name": "inside", "trans": ["在里面"]}, {"name": "shout", "trans": ["大声说，叫，嚷"]},
    {"name": "knock", "trans": ["敲，击"]}, {"name": "knock on the door", "trans": ["敲门"]},
    {"name": "treat", "trans": ["招待，款待"]}, {"name": "trick", "trans": ["诡计，把戏"]},
    {"name": "trick or treat", "trans": ["不给糖就捣蛋"]}, {"name": "if", "trans": ["如果"]},
    {"name": "special", "trans": ["特殊的，特别的"]}, {"name": "question", "trans": ["问题"]},
    {"name": "dumpling", "trans": ["汤圆，饺子"]}, {"name": "rice dumpling", "trans": ["粽子"]},
    {"name": "grandparent", "trans": ["祖父（母）"]}, {"name": "thing", "trans": ["东西，物品"]},
    {"name": "lion", "trans": ["狮子"]}, {"name": "firework", "trans": ["烟火，烟花"]},
    {"name": "find out", "trans": ["发现"]}, {"name": "more", "trans": ["更多"]},
    {"name": "radio", "trans": ["收音机"]}, {"name": "take photos", "trans": ["拍照"]},
    {"name": "at night", "trans": ["在夜里"]}, {"name": "seem", "trans": ["好像，似乎，看来"]},
    {"name": "different", "trans": ["不同的"]}, {"name": "important", "trans": ["重要的"]},
    {"name": "most", "trans": ["大多数，大部分"]}, {"name": "off", "trans": ["离开，脱离"]},
    {"name": "set off", "trans": ["爆炸"]}, {"name": "packet", "trans": ["小包；（一）包"]},
    {"name": "red packet", "trans": ["红包"]}, {"name": "lifestyle", "trans": ["生活方式"]},
    {"name": "noon", "trans": ["正午"]}, {"name": "hamburger", "trans": ["汉堡包"]},
    {"name": "keep", "trans": ["保持"]}, {"name": "lemon", "trans": ["柠檬"]},
    {"name": "watermelon", "trans": ["西瓜"]}, {"name": "chocolate", "trans": ["巧克力"]},
    {"name": "carrot", "trans": ["胡萝卜"]}, {"name": "meat", "trans": ["肉"]},
    {"name": "pork", "trans": ["猪肉"]}, {"name": "beef", "trans": ["牛肉"]},
    {"name": "sweet", "trans": ["（英）糖果，甜点"]}, {"name": "sugar", "trans": ["食糖，糖"]},
    {"name": "snack", "trans": ["小吃，零食"]}, {"name": "meal", "trans": ["一餐"]},
    {"name": "pear", "trans": ["梨"]}, {"name": "health", "trans": ["健康"]},
    {"name": "fit", "trans": ["健康的"]}, {"name": "tooth", "trans": ["牙齿"]},
    {"name": "computer game", "trans": ["电脑游戏"]}, {"name": "cola", "trans": ["可乐饮料"]},
    {"name": "change", "trans": ["改变，变化"]}, {"name": "plan", "trans": ["打算，计划"]},
    {"name": "pool", "trans": ["水池，水塘"]}, {"name": "swimming pool", "trans": ["游泳池"]},
    {"name": "piece", "trans": ["块"]}, {"name": "a piece of", "trans": ["一片……"]},
    {"name": "glass", "trans": ["玻璃杯，玻璃"]}, {"name": "cup", "trans": ["茶杯，杯"]},
    {"name": "plate", "trans": ["盘子"]}, {"name": "carton", "trans": ["盒"]},
    {"name": "bottle", "trans": ["瓶子"]}, {"name": "salt", "trans": ["盐"]},
    {"name": "kilo", "trans": ["千克，公斤"]}, {"name": "less", "trans": ["较少，更少"]},
    {"name": "than", "trans": ["比"]}, {"name": "take a walk", "trans": ["散步"]},
    {"name": "total", "trans": ["总的，总计的，全部的"]}, {"name": "number", "trans": ["数，数量"]},
    {"name": "score", "trans": ["得分"]}, {"name": "point", "trans": ["分数"]},
    {"name": "order", "trans": ["点菜"]}, {"name": "menu", "trans": ["菜单"]},
    {"name": "bean", "trans": ["豆，豆科植物"]}, {"name": "all right", "trans": ["行了，好吧"]},
    {"name": "taste", "trans": ["有……的味道"]}, {"name": "energy", "trans": ["能量"]},
    {"name": "whole", "trans": ["整个的"]}, {"name": "shopping", "trans": ["购物"]},
    {"name": "mall", "trans": ["大型购物中心"]}, {"name": "down", "trans": ["沿着，向下"]},
    {"name": "hate", "trans": ["讨厌，恨"]}, {"name": "well", "trans": ["好吧，那么，哎呀"]},
    {"name": "money", "trans": ["钱"]}, {"name": "wallet", "trans": ["钱包"]},
    {"name": "carry", "trans": ["拿，提，搬"]}, {"name": "bookshop", "trans": ["书店"]},
    {"name": "gift", "trans": ["礼物"]}, {"name": "CD", "trans": ["光盘，激光唱片"]},
    {"name": "maybe", "trans": ["也许，可能"]}, {"name": "be interested in", "trans": ["对……感兴趣"]},
    {"name": "stamp", "trans": ["邮票"]}, {"name": "collect", "trans": ["收集，搜集"]},
    {"name": "You're welcome", "trans": ["不用谢，不客气"]}, {"name": "shopkeeper", "trans": ["店主，售货员"]},
    {"name": "just a minute", "trans": ["稍等片刻"]}, {"name": "take a look", "trans": ["看一看"]},
    {"name": "cost", "trans": ["值多少钱，需付费"]}, {"name": "cheap", "trans": ["便宜的"]},
    {"name": "last", "trans": ["最近的；上一个"]}, {"name": "hair clip", "trans": ["发卡，发夹"]},
    {"name": "pink", "trans": ["粉红色的"]}, {"name": "pretty", "trans": ["漂亮的，俊俏的"]},
    {"name": "enough", "trans": ["足够，充分"]}, {"name": "different from", "trans": ["与……不同"]},
    {"name": "paper", "trans": ["纸"]}, {"name": "item", "trans": ["一件物品，项目"]},
    {"name": "T-shirt", "trans": ["T恤衫"]}, {"name": "poor", "trans": ["贫穷的，可怜的"]},
    {"name": "area", "trans": ["地区"]}, {"name": "pocket", "trans": ["口袋"]},
    {"name": "pocket money", "trans": ["零花钱"]}, {"name": "pair", "trans": ["双，对，副"]},
    {"name": "a pair of", "trans": ["一双，一副"]}, {"name": "size", "trans": ["尺码，大小"]},
    {"name": "try on", "trans": ["试穿，试试看"]}, {"name": "fit", "trans": ["适合，合身"]},
    {"name": "expensive", "trans": ["昂贵的"]}, {"name": "another", "trans": ["别的/不同的/又一/另一"]},
    {"name": "price", "trans": ["价格，价钱"]}, {"name": "large", "trans": ["大的，大型号的"]},
    {"name": "note", "trans": ["笔记，便条"]}, {"name": "bus stop", "trans": ["公共汽车站"]},
    {"name": "restaurant", "trans": ["餐馆"]}, {"name": "top", "trans": ["最高的"]},
    {"name": "fashion", "trans": ["时装，时尚，风尚"]}, {"name": "think about", "trans": ["考虑"]},
    {"name": "spend", "trans": ["度过"]}, {"name": "lazy", "trans": ["懒惰的"]},
    {"name": "lend", "trans": ["借给"]}, {"name": "lady", "trans": ["女士，夫人"]},
    {"name": "gentleman", "trans": ["先生"]}, {"name": "style", "trans": ["风格，款式"]},
    {"name": "comfortable", "trans": ["舒适的"]}, {"name": "popular", "trans": ["受喜爱的，受欢迎的"]},
    {"name": "among", "trans": ["在（三者或以上）中"]}, {"name": "purple", "trans": ["紫色的"]},
    {"name": "grey", "trans": ["灰色的"]}, {"name": "smart", "trans": ["衣着讲究的，精干的"]},
    {"name": "cool", "trans": ["酷的，绝妙的"]}, {"name": "cotton", "trans": ["棉，棉织物"]},
    {"name": "silk", "trans": ["丝；丝绸"]}, {"name": "wool", "trans": ["羊毛，羊绒"]},
    {"name": "leather", "trans": ["皮革"]}, {"name": "blouse", "trans": ["短上衣，衬衫"]},
    {"name": "tie", "trans": ["领带"]}, {"name": "scarf", "trans": ["围巾"]},
    {"name": "jeans", "trans": ["牛仔裤"]}, {"name": "boot", "trans": ["靴子"]},
    {"name": "glove", "trans": ["手套"]}, {"name": "hat", "trans": ["帽子"]},
    {"name": "jacket", "trans": ["夹克衫"]}, {"name": "trainer", "trans": ["（英）运动鞋"]},
    {"name": "both", "trans": ["两个（都）"]}, {"name": "be made of", "trans": ["由……制成"]},
    {"name": "write to", "trans": ["写信给"]}, {"name": "wait for", "trans": ["等候"]},
    {"name": "look for", "trans": ["寻找"]}, {"name": "lie", "trans": ["平放，躺"]},
    {"name": "go for", "trans": ["去从事"]}, {"name": "suitable for", "trans": ["适合于"]},
    {"name": "think of", "trans": ["认为"]}, {"name": "material", "trans": ["材料"]},
    {"name": "design", "trans": ["设计，构思"]}, {"name": "model", "trans": ["模特，模型"]},
    {"name": "dark", "trans": ["昏暗的"]}, {"name": "include", "trans": ["包括"]},
    {"name": "have breakfast/lunch/dinner", "trans": ["吃早/中/晚饭"]},
]

GRADE_7_LOWER = [
    {"name": "palace", "trans": ["皇宫，宫殿"]}, {"name": "next to", "trans": ["紧邻，在…近旁"]},
    {"name": "town", "trans": ["镇，城镇"]}, {"name": "Canada", "trans": ["加拿大"]},
    {"name": "France", "trans": ["法国"]}, {"name": "Japan", "trans": ["日本"]},
    {"name": "Russia", "trans": ["俄罗斯"]}, {"name": "UK", "trans": ["英国"]},
    {"name": "London", "trans": ["伦敦"]}, {"name": "country", "trans": ["国家"]},
    {"name": "capital", "trans": ["首都"]}, {"name": "mile", "trans": ["英里"]},
    {"name": "garden", "trans": ["花园，果园"]}, {"name": "flat", "trans": ["公寓，套房"]},
    {"name": "centre", "trans": ["中心"]}, {"name": "living room", "trans": ["起居室，客厅"]},
    {"name": "share", "trans": ["合用；分享"]}, {"name": "share sth with sb", "trans": ["与某人合用/分享某物"]},
    {"name": "bedroom", "trans": ["卧室"]}, {"name": "own", "trans": ["自己的"]},
    {"name": "bathroom", "trans": ["浴室，盥洗室"]}, {"name": "balcony", "trans": ["阳台"]},
    {"name": "beach", "trans": ["海滩"]}, {"name": "sea", "trans": ["海"]},
    {"name": "dining room", "trans": ["餐厅"]}, {"name": "zero", "trans": ["零"]},
    {"name": "hundred", "trans": ["百"]}, {"name": "thousand", "trans": ["千"]},
    {"name": "million", "trans": ["百万"]}, {"name": "foot", "trans": ["英尺 (pl. feet)"]},
    {"name": "square", "trans": ["平方的"]}, {"name": "metre", "trans": ["米，公尺"]},
    {"name": "area", "trans": ["面积"]}, {"name": "fork", "trans": ["叉，餐叉"]},
    {"name": "fridge", "trans": ["冰箱"]}, {"name": "knife", "trans": ["刀 (pl. knives)"]},
    {"name": "lamp", "trans": ["灯，台灯"]}, {"name": "shower", "trans": ["淋浴器；淋浴"]},
    {"name": "sofa", "trans": ["沙发"]}, {"name": "video", "trans": ["录像；视频"]},
    {"name": "be full of", "trans": ["满是"]}, {"name": "of one's own", "trans": ["属于某人自己的"]},
    {"name": "some day", "trans": ["将来有一天，总有一天"]}, {"name": "may", "trans": ["可以；也许，可能"]},
    {"name": "message", "trans": ["消息，音信"]}, {"name": "take a message", "trans": ["传个话，捎个口信"]},
    {"name": "call sb back", "trans": ["回电话"]}, {"name": "double", "trans": ["双的；两倍的"]},
    {"name": "study", "trans": ["书房"]}, {"name": "machine", "trans": ["机器"]},
    {"name": "washing machine", "trans": ["洗衣机"]}, {"name": "at the foot of", "trans": ["在…脚下"]},
    {"name": "field", "trans": ["地，田"]}, {"name": "football field", "trans": ["足球场"]},
    {"name": "home cinema", "trans": ["家庭影院"]}, {"name": "invite", "trans": ["邀请"]},
    {"name": "stay", "trans": ["停留，逗留"]}, {"name": "neighbour", "trans": ["邻居"]},
    {"name": "wow", "trans": ["哇，呀"]}, {"name": "will", "trans": ["将，将会"]},
    {"name": "visitor", "trans": ["访问者，参观者"]}, {"name": "like", "trans": ["像，类似"]},
    {"name": "waiter", "trans": ["（餐馆等的）服务员"]}, {"name": "neighbourhood", "trans": ["街区，居民区"]},
    {"name": "helpful", "trans": ["愿意帮忙的；有用的"]}, {"name": "volunteer", "trans": ["志愿者，义务工作者"]},
    {"name": "community", "trans": ["社区"]}, {"name": "skill", "trans": ["技能，技巧"]},
    {"name": "help sb with sth", "trans": ["帮助某人解决某种困难"]}, {"name": "problem", "trans": ["问题，难题"]},
    {"name": "something", "trans": ["某事，某物"]}, {"name": "engineer", "trans": ["工程师；技师"]},
    {"name": "check", "trans": ["检查；核实"]}, {"name": "broken", "trans": ["损坏了的；破碎的"]},
    {"name": "someone", "trans": ["某人"]}, {"name": "fix", "trans": ["修理"]},
    {"name": "anyone", "trans": ["任何人"]}, {"name": "college", "trans": ["学院"]},
    {"name": "do some shopping", "trans": ["买东西"]}, {"name": "lucky", "trans": ["幸运的"]},
    {"name": "the day after tomorrow", "trans": ["后天"]}, {"name": "fire", "trans": ["火"]},
    {"name": "make a fire", "trans": ["生火"]}, {"name": "manager", "trans": ["经理"]},
    {"name": "office", "trans": ["办公室"]}, {"name": "office worker", "trans": ["办公室职员，上班族"]},
    {"name": "policeman", "trans": ["警察 (pl. policemen)"]}, {"name": "postman", "trans": ["邮递员 (pl. postmen)"]},
    {"name": "company", "trans": ["公司"]}, {"name": "station", "trans": ["局，所，站"]},
    {"name": "police station", "trans": ["警察局"]}, {"name": "post", "trans": ["邮政"]},
    {"name": "post office", "trans": ["邮局"]}, {"name": "person", "trans": ["人"]},
    {"name": "job", "trans": ["工作"]}, {"name": "elder", "trans": ["年纪较长的"]},
    {"name": "by train/bus/ship/bike", "trans": ["乘火车/公共汽车/轮船/骑自行车"]},
    {"name": "future", "trans": ["将来"]}, {"name": "artist", "trans": ["艺术家，（尤指）画家"]},
    {"name": "sound", "trans": ["听起来"]}, {"name": "sick", "trans": ["生病的；恶心的"]},
    {"name": "notice", "trans": ["布告，通知"]}, {"name": "information", "trans": ["信息"]},
    {"name": "below", "trans": ["下面"]}, {"name": "better", "trans": ["（good/well的比较级）较好，更好"]},
    {"name": "anything", "trans": ["任何事"]}, {"name": "worry about", "trans": ["为…担心"]},
    {"name": "group", "trans": ["组，群"]}, {"name": "mine", "trans": ["我的"]},
    {"name": "nothing", "trans": ["没有什么"]}, {"name": "wait a minute", "trans": ["等一会儿"]},
    {"name": "yuan", "trans": ["元（人民币单位）"]}, {"name": "tin", "trans": ["罐，听"]},
    {"name": "pizza", "trans": ["比萨饼"]}, {"name": "exchange student", "trans": ["交流学生"]},
    {"name": "quiet", "trans": ["安静的；寂静的"]}, {"name": "air", "trans": ["空气，大气"]},
    {"name": "fresh", "trans": ["新鲜的"]}, {"name": "local", "trans": ["本地的，当地的"]},
    {"name": "jogging", "trans": ["慢跑锻炼"]}, {"name": "underground", "trans": ["地铁"]},
    {"name": "famous", "trans": ["出名的，著名的"]}, {"name": "western", "trans": ["西方的"]},
    {"name": "opera", "trans": ["歌剧，戏剧"]}, {"name": "theatre", "trans": ["戏院，剧场"]},
    {"name": "miss", "trans": ["错过，失去"]}, {"name": "forward", "trans": ["向前，前进"]},
    {"name": "look forward to", "trans": ["盼望，期待"]}, {"name": "soon", "trans": ["很快，不久"]},
    {"name": "postcard", "trans": ["明信片"]}, {"name": "key", "trans": ["钥匙"]},
    {"name": "ring", "trans": ["环，圈，戒指"]}, {"name": "key ring", "trans": ["钥匙扣"]},
    {"name": "yours", "trans": ["你的，你们的"]}, {"name": "ours", "trans": ["我们的"]},
    {"name": "theirs", "trans": ["他（她，它）们的"]}, {"name": "hers", "trans": ["她的"]},
    {"name": "all over", "trans": ["到处，遍及"]}, {"name": "pencil case", "trans": ["笔盒，笔袋"]},
    {"name": "work", "trans": ["作品，著作"]}, {"name": "work of art", "trans": ["艺术品"]},
    {"name": "painting", "trans": ["绘画，油画"]}, {"name": "row", "trans": ["划（船）"]},
    {"name": "hotel", "trans": ["旅馆"]}, {"name": "hometown", "trans": ["家乡"]},
    {"name": "raise", "trans": ["饲养"]}, {"name": "grow", "trans": ["（使）生长，发育；长大，长高"]},
    {"name": "wheat", "trans": ["小麦"]}, {"name": "friendly", "trans": ["友好的"]},
    {"name": "smell", "trans": ["嗅，闻到；气味"]}, {"name": "drive", "trans": ["驾车送（人）；驾驶，开车"]},
    {"name": "follow", "trans": ["跟随；仿效"]}, {"name": "path", "trans": ["小路，小径"]},
    {"name": "have to", "trans": ["不得不，必须"]}, {"name": "north", "trans": ["北，北方"]},
    {"name": "west", "trans": ["西，西方"]}, {"name": "south", "trans": ["南，南方"]},
    {"name": "east", "trans": ["东，东方"]}, {"name": "trip", "trans": ["旅行，旅游"]},
    {"name": "kilometre", "trans": ["千米，公里"]}, {"name": "everybody", "trans": ["每人，人人"]},
    {"name": "straight", "trans": ["径直地；笔直的"]}, {"name": "bamboo", "trans": ["竹"]},
    {"name": "all day long", "trans": ["整天地"]}, {"name": "along", "trans": ["沿着，顺着"]},
    {"name": "road", "trans": ["路，道路"]}, {"name": "king", "trans": ["国王"]},
    {"name": "remember", "trans": ["记得，记住"]}, {"name": "dangerous", "trans": ["危险的"]},
    {"name": "forest", "trans": ["森林"]}, {"name": "funny", "trans": ["好笑的，滑稽的"]},
    {"name": "laugh", "trans": ["笑，大笑"]}, {"name": "giraffe", "trans": ["长颈鹿"]},
    {"name": "quite", "trans": ["相当，非常"]}, {"name": "neck", "trans": ["脖子"]},
    {"name": "leaf", "trans": ["（树、菜）叶 (pl. leaves)"]}, {"name": "north-east", "trans": ["东北方"]},
    {"name": "bridge", "trans": ["桥"]}, {"name": "cross", "trans": ["穿过，横过"]},
    {"name": "cage", "trans": ["笼子，鸟笼"]}, {"name": "across", "trans": ["在…对面；穿过，横过"]},
    {"name": "outside", "trans": ["在…外面"]}, {"name": "above", "trans": ["在…上面"]},
    {"name": "sign", "trans": ["指示牌"]}, {"name": "bench", "trans": ["长椅"]},
    {"name": "treasure", "trans": ["宝藏"]}, {"name": "turning", "trans": ["转弯处"]},
    {"name": "traffic", "trans": ["交通，来往车辆"]}, {"name": "traffic lights", "trans": ["红绿灯"]},
    {"name": "should", "trans": ["应当，应该"]}, {"name": "crossing", "trans": ["交叉路口"]},
    {"name": "corner", "trans": ["拐角，街角；角落"]}, {"name": "prepare", "trans": ["准备"]},
    {"name": "prepare for", "trans": ["为…准备"]}, {"name": "plenty", "trans": ["大量，充足"]},
    {"name": "plenty of", "trans": ["大量，足够"]}, {"name": "exit", "trans": ["出口"]},
    {"name": "bank", "trans": ["银行"]}, {"name": "amazing", "trans": ["令人吃惊的，惊人的"]},
    {"name": "same", "trans": ["同一的，相同的"]}, {"name": "birth", "trans": ["出生，诞生"]},
    {"name": "stop doing sth", "trans": ["停止做某事"]}, {"name": "times", "trans": ["（用于比较级）倍"]},
    {"name": "earth", "trans": ["地球，大地"]}, {"name": "bone", "trans": ["骨头"]},
    {"name": "back", "trans": ["后部；背部"]}, {"name": "fat", "trans": ["脂肪"]},
    {"name": "fact", "trans": ["事实"]}, {"name": "usual", "trans": ["通常的，平常的"]},
    {"name": "as usual", "trans": ["照例，像往常一样"]}, {"name": "sit down", "trans": ["坐下"]},
    {"name": "suddenly", "trans": ["突然"]}, {"name": "whisper", "trans": ["低语，耳语"]},
    {"name": "bush", "trans": ["灌木丛"]}, {"name": "turn around", "trans": ["转身；（使）翻转"]},
    {"name": "anybody", "trans": ["任何人"]}, {"name": "nobody", "trans": ["没有人，无人"]},
    {"name": "reply", "trans": ["答复，回答"]}, {"name": "strange", "trans": ["奇怪的；陌生的"]},
    {"name": "leave", "trans": ["离开"]}, {"name": "quickly", "trans": ["迅速地，飞快地"]},
    {"name": "on one's way", "trans": ["在…路上"]}, {"name": "happen", "trans": ["发生"]},
    {"name": "everything", "trans": ["每件事，每样事物，一切"]}, {"name": "wonder", "trans": ["琢磨，想知道"]},
    {"name": "carefully", "trans": ["仔细地，认真地"]}, {"name": "search", "trans": ["搜查，搜索"]},
    {"name": "himself", "trans": ["他自己"]}, {"name": "say to oneself", "trans": ["自言自语"]},
    {"name": "weak", "trans": ["虚弱的，无力的"]}, {"name": "miaow", "trans": ["（猫叫声）喵"]},
    {"name": "pick", "trans": ["拾起"]}, {"name": "pick up", "trans": ["拿起，举起"]},
    {"name": "surprised", "trans": ["吃惊的，惊讶的"]}, {"name": "later", "trans": ["随后，后来"]},
    {"name": "run away", "trans": ["逃离，跑开"]}, {"name": "somebody", "trans": ["某人，有人"]},
    {"name": "ago", "trans": ["以前"]}, {"name": "the day before yesterday", "trans": ["前天"]},
    {"name": "centimetre", "trans": ["厘米，公分"]}, {"name": "dodo", "trans": ["渡渡鸟"]},
    {"name": "snake", "trans": ["蛇"]}, {"name": "camel", "trans": ["骆驼"]},
    {"name": "ant", "trans": ["蚂蚁"]}, {"name": "little", "trans": ["不多的，少数的"]},
    {"name": "dry", "trans": ["干的；干燥的"]}, {"name": "without", "trans": ["没有"]},
    {"name": "be afraid of", "trans": ["害怕"]}, {"name": "not any more", "trans": ["再也不，不再"]},
    {"name": "hear of", "trans": ["听说，知道"]}, {"name": "the other day", "trans": ["那天，前几天"]},
    {"name": "at the same time", "trans": ["同时"]}, {"name": "chalk", "trans": ["粉笔"]},
    {"name": "sandwich", "trans": ["三明治"]}, {"name": "all over the world", "trans": ["遍及全世界"]},
    {"name": "by", "trans": ["不迟于，在…之前"]}, {"name": "use", "trans": ["使用，利用；用途"]},
    {"name": "per", "trans": ["每，每一"]}, {"name": "at least", "trans": ["至少"]},
    {"name": "inch", "trans": ["英寸"]}, {"name": "ask for", "trans": ["请求；要"]},
    {"name": "outdoor", "trans": ["户外的"]}, {"name": "hurry", "trans": ["急忙，匆忙"]},
    {"name": "hurry up", "trans": ["快点，赶快"]}, {"name": "complain", "trans": ["抱怨"]},
    {"name": "camping", "trans": ["野营"]}, {"name": "cycling", "trans": ["骑自行车运动"]},
    {"name": "riding", "trans": ["骑马"]}, {"name": "skating", "trans": ["溜冰"]},
    {"name": "ride", "trans": ["骑（马、自行车等）"]}, {"name": "rabbit", "trans": ["兔，家兔"]},
    {"name": "hole", "trans": ["洞"]}, {"name": "pass", "trans": ["经过；通过"]},
    {"name": "dear", "trans": ["哎呀，天哪，啊"]}, {"name": "watch", "trans": ["手表"]},
    {"name": "stand up", "trans": ["站起身，起立"]}, {"name": "get away", "trans": ["逃脱，离开"]},
    {"name": "fall", "trans": ["落下，掉落；倒"]}, {"name": "hit", "trans": ["到达；击中，撞"]},
    {"name": "herself", "trans": ["她自己"]}, {"name": "alone", "trans": ["独自，单独"]},
    {"name": "low", "trans": ["低的，矮的"]}, {"name": "locked", "trans": ["锁上的"]},
    {"name": "into", "trans": ["到…里面"]}, {"name": "side", "trans": ["侧，边"]},
    {"name": "through", "trans": ["穿过，通过"]}, {"name": "go through", "trans": ["通过"]},
    {"name": "put up", "trans": ["搭，竖立"]}, {"name": "tent", "trans": ["帐篷"]},
    {"name": "wood", "trans": ["木头，木材"]}, {"name": "period", "trans": ["一段时间，时期"]},
    {"name": "dynasty", "trans": ["朝代，王朝"]}, {"name": "century", "trans": ["世纪，百年"]},
    {"name": "Italian", "trans": ["意大利的"]}, {"name": "province", "trans": ["省"]},
    {"name": "from then on", "trans": ["从那时起"]}, {"name": "excited", "trans": ["激动的"]},
    {"name": "mobile phone", "trans": ["手机"]}, {"name": "a little", "trans": ["一点，少许"]},
    {"name": "decide", "trans": ["决定"]}, {"name": "enter", "trans": ["进入"]},
    {"name": "towards", "trans": ["向，朝"]}, {"name": "forget", "trans": ["忘记"]},
    {"name": "too...to...", "trans": ["太…而不能…"]}, {"name": "reach", "trans": ["伸手（脚）够到"]},
    {"name": "climb", "trans": ["爬，攀登"]}, {"name": "fail", "trans": ["失败"]},
    {"name": "ability", "trans": ["能力"]}, {"name": "believe", "trans": ["相信"]},
    {"name": "believe it or not", "trans": ["信不信由你"]}, {"name": "look out", "trans": ["留神，当心"]},
    {"name": "seat", "trans": ["座位"]}, {"name": "send", "trans": ["发送；邮寄"]},
    {"name": "even", "trans": ["甚至"]}, {"name": "able", "trans": ["能，能够"]},
    {"name": "pay", "trans": ["付费"]}, {"name": "pay for", "trans": ["为…付款"]},
    {"name": "notebook", "trans": ["笔记本"]}, {"name": "brave", "trans": ["勇敢的"]},
    {"name": "save", "trans": ["救，救助"]}, {"name": "save...from...", "trans": ["从…中救出…"]},
    {"name": "smoke", "trans": ["烟，烟雾；吸（烟），抽（烟）"]}, {"name": "next door", "trans": ["在隔壁"]},
    {"name": "badly", "trans": ["严重地，厉害地"]}, {"name": "hurt", "trans": ["受伤的；使受伤，伤害；疼"]},
    {"name": "could", "trans": ["（can的过去式）可以，能，会"]}, {"name": "pour", "trans": ["倾倒"]},
    {"name": "protect", "trans": ["保护"]}, {"name": "rush", "trans": ["冲，奔"]},
    {"name": "wet", "trans": ["湿的；未干的；有雨的"]}, {"name": "blanket", "trans": ["毯子"]},
    {"name": "fireman", "trans": ["消防员 (pl. firemen)"]}, {"name": "put out", "trans": ["扑灭"]},
    {"name": "burn", "trans": ["烧伤；烧"]}, {"name": "moment", "trans": ["时刻；片刻，瞬间"]},
    {"name": "nod", "trans": ["点头"]}, {"name": "careful", "trans": ["仔细的，认真的；小心的"]},
    {"name": "reporter", "trans": ["记者"]}, {"name": "news", "trans": ["新闻，消息"]},
    {"name": "newspaper", "trans": ["报纸"]}, {"name": "rubbish", "trans": ["垃圾，废弃物"]},
    {"name": "bin", "trans": ["垃圾箱"]}, {"name": "by the way", "trans": ["顺便问一下，顺便说说"]},
    {"name": "camera", "trans": ["照相机"]}, {"name": "no problem", "trans": ["没问题"]},
    {"name": "X-ray", "trans": ["X光，X射线"]}, {"name": "term", "trans": ["学期"]},
    {"name": "hard", "trans": ["努力地；费力地"]}, {"name": "article", "trans": ["文章"]},
    {"name": "careless", "trans": ["粗心的"]}, {"name": "do one's best", "trans": ["尽某人最大努力"]},
    {"name": "piano", "trans": ["钢琴"]}, {"name": "do well in", "trans": ["做得好"]},
    {"name": "violin", "trans": ["小提琴"]}, {"name": "at the age of", "trans": ["在…岁时"]},
    {"name": "teach", "trans": ["教；演示；展示"]}, {"name": "sir", "trans": ["先生"]},
    {"name": "madam", "trans": ["女士，夫人"]}, {"name": "recommend", "trans": ["推荐"]},
    {"name": "award", "trans": ["奖；奖品；奖金"]}, {"name": "part", "trans": ["部分"]},
    {"name": "take part in", "trans": ["参加"]}, {"name": "lose", "trans": ["迷失；丢失"]},
    {"name": "lose one's way", "trans": ["迷路"]}, {"name": "before", "trans": ["到…为止；在…之前"]},
    {"name": "hear from", "trans": ["收到…的来信"]}, {"name": "Yours faithfully", "trans": ["（用于信结尾签名前）您忠实的"]},
    {"name": "pet", "trans": ["宠物"]}, {"name": "rude", "trans": ["粗鲁的，不礼貌的"]},
    {"name": "goldfish", "trans": ["金鱼"]}, {"name": "mouse", "trans": ["老鼠，耗子 (pl. mice)"]},
    {"name": "parrot", "trans": ["鹦鹉"]}, {"name": "knee", "trans": ["膝，膝盖"]},
    {"name": "hold", "trans": ["握住，拿"]}, {"name": "feed", "trans": ["喂，喂养"]},
    {"name": "poem", "trans": ["诗歌"]}, {"name": "wide", "trans": ["充分地"]},
    {"name": "hide", "trans": ["藏，隐藏"]}, {"name": "build", "trans": ["建造，建筑"]},
    {"name": "camp", "trans": ["营地；阵营"]}, {"name": "stick", "trans": ["树枝；棍，棒"]},
    {"name": "bark", "trans": ["（狗）叫，吠"]}, {"name": "fight", "trans": ["打仗（架）；与…打仗（架）"]},
    {"name": "look after", "trans": ["照顾"]}, {"name": "till", "trans": ["到…时，直到…为止"]},
    {"name": "end", "trans": ["末尾，终点"]},
]

GRADE_8_UPPER = [
    {"name": "thirsty", "trans": ["口渴的"]}, {"name": "honest", "trans": ["诚实的；正直的"]},
    {"name": "secret", "trans": ["秘密"]}, {"name": "keep a secret", "trans": ["保守秘密"]},
    {"name": "joy", "trans": ["欢乐，高兴；乐趣"]}, {"name": "care", "trans": ["关心，关注，在意"]},
    {"name": "care about", "trans": ["关心，关怀"]}, {"name": "yourself", "trans": ["你自己"]},
    {"name": "teenager", "trans": ["青少年"]}, {"name": "magazine", "trans": ["杂志"]},
    {"name": "good-looking", "trans": ["好看的，漂亮的"]}, {"name": "humorous", "trans": ["幽默的"]},
    {"name": "polite", "trans": ["礼貌的"]}, {"name": "tidy", "trans": ["爱整洁的，整洁的"]},
    {"name": "make", "trans": ["成为；适合"]}, {"name": "trust", "trans": ["信任"]},
    {"name": "lie", "trans": ["谎言"]}, {"name": "joke", "trans": ["玩笑"]},
    {"name": "true", "trans": ["确实的；的确"]}, {"name": "generous", "trans": ["慷慨的，大方的"]},
    {"name": "willing", "trans": ["乐意的，愿意的"]}, {"name": "anytime", "trans": ["在任何时候"]},
    {"name": "voice", "trans": ["嗓音"]}, {"name": "singer", "trans": ["歌手"]},
    {"name": "almost", "trans": ["几乎，差不多"]}, {"name": "round", "trans": ["圆形的"]},
    {"name": "sense", "trans": ["感觉；观念，意识"]}, {"name": "humour", "trans": ["幽默"]},
    {"name": "bored", "trans": ["无聊的"]}, {"name": "fit", "trans": ["可容纳，装进"]},
    {"name": "knock", "trans": ["碰，撞"]}, {"name": "onto", "trans": ["到…的上面"]},
    {"name": "straight", "trans": ["笔直的"]}, {"name": "sweet", "trans": ["可爱的，惹人喜爱的"]},
    {"name": "smile", "trans": ["微笑"]}, {"name": "personality", "trans": ["个性"]},
    {"name": "choose", "trans": ["选择；挑选"]}, {"name": "worse", "trans": ["更差，更糟，更坏"]},
    {"name": "worst", "trans": ["最差，最糟，最坏"]}, {"name": "height", "trans": ["高，高度"]},
    {"name": "weight", "trans": ["重量"]}, {"name": "competition", "trans": ["竞赛，比赛；竞争"]},
    {"name": "test", "trans": ["测试，考查"]}, {"name": "swimmer", "trans": ["游泳者"]},
    {"name": "plan", "trans": ["打算，计划"]}, {"name": "social", "trans": ["社会的"]},
    {"name": "social worker", "trans": ["社会工作者"]}, {"name": "ponytail", "trans": ["马尾辫"]},
    {"name": "shy", "trans": ["害羞的"]}, {"name": "square", "trans": ["方形的"]},
    {"name": "smiling", "trans": ["微笑的，带着笑意的"]}, {"name": "handsome", "trans": ["英俊的"]},
    {"name": "fat", "trans": ["胖的"]}, {"name": "hard-working", "trans": ["勤奋的，工作努力的"]},
    {"name": "patient", "trans": ["耐心的"]}, {"name": "unhappy", "trans": ["不快乐的，悲伤的"]},
    {"name": "excellent", "trans": ["杰出的，极好的"]}, {"name": "advertisement", "trans": ["广告"]},
    {"name": "British", "trans": ["英国的"]}, {"name": "biscuit", "trans": ["饼干"]},
    {"name": "lorry", "trans": ["卡车"]}, {"name": "rubber", "trans": ["橡皮"]},
    {"name": "American", "trans": ["美国的"]}, {"name": "eraser", "trans": ["橡皮"]},
    {"name": "soccer", "trans": ["英式足球"]}, {"name": "vacation", "trans": ["假期"]},
    {"name": "cookie", "trans": ["饼干"]}, {"name": "fall", "trans": ["秋天"]},
    {"name": "store", "trans": ["商店"]}, {"name": "truck", "trans": ["卡车"]},
    {"name": "yard", "trans": ["院子"]}, {"name": "movie", "trans": ["电影"]},
    {"name": "mixed", "trans": ["男女混合的；混合的"]}, {"name": "French", "trans": ["法语"]},
    {"name": "foreign", "trans": ["外国的"]}, {"name": "language", "trans": ["语言"]},
    {"name": "during", "trans": ["在…期间"]}, {"name": "discuss", "trans": ["讨论，议论"]},
    {"name": "in class", "trans": ["在课堂上"]}, {"name": "guy", "trans": ["家伙"]},
    {"name": "buddy", "trans": ["好朋友；搭档"]}, {"name": "offer", "trans": ["主动提出，自愿给予"]},
    {"name": "end", "trans": ["结束"]}, {"name": "baseball", "trans": ["棒球"]},
    {"name": "win", "trans": ["赢得；赢，获胜"]}, {"name": "least", "trans": ["最少的；最小的"]},
    {"name": "further", "trans": ["较远"]}, {"name": "furthest", "trans": ["最远"]},
    {"name": "spend", "trans": ["花费"]}, {"name": "uniform", "trans": ["制服"]},
    {"name": "chess", "trans": ["国际象棋"]}, {"name": "at most", "trans": ["至多，不超过"]},
    {"name": "daily", "trans": ["每日的，日常的"]}, {"name": "weekly", "trans": ["每周的"]},
    {"name": "quick", "trans": ["快的"]}, {"name": "through", "trans": ["自始至终，从头到尾"]},
    {"name": "look through", "trans": ["浏览，快速查看"]}, {"name": "real", "trans": ["真实的，真的"]},
    {"name": "at first", "trans": ["起初，首先"]}, {"name": "keep on doing", "trans": ["继续，重复做某事"]},
    {"name": "finish", "trans": ["完成；结束"]}, {"name": "lunchtime", "trans": ["午餐时间"]},
    {"name": "physics", "trans": ["物理"]}, {"name": "badminton", "trans": ["羽毛球"]},
    {"name": "ideal", "trans": ["理想的"]}, {"name": "come on", "trans": ["来吧；赶快"]},
    {"name": "ourselves", "trans": ["我们自己"]}, {"name": "enjoy oneself", "trans": ["玩得愉快"]},
    {"name": "Australia", "trans": ["澳大利亚"]}, {"name": "take care", "trans": ["保重"]},
    {"name": "coffee", "trans": ["咖啡"]}, {"name": "top", "trans": ["顶部，上面"]},
    {"name": "president", "trans": ["总统，国家主席"]}, {"name": "wide", "trans": ["宽的，宽广的"]},
    {"name": "steel", "trans": ["钢"]}, {"name": "ton", "trans": ["吨"]},
    {"name": "fine", "trans": ["够好，蛮不错"]}, {"name": "join", "trans": ["加入，参加"]},
    {"name": "myself", "trans": ["我自己"]}, {"name": "shine", "trans": ["发光，照耀"]},
    {"name": "clear", "trans": ["晴朗的，清晰的"]}, {"name": "sky", "trans": ["天，天空"]},
    {"name": "journey", "trans": ["旅行，旅程"]}, {"name": "boring", "trans": ["乏味的"]},
    {"name": "finally", "trans": ["最后"]}, {"name": "arrive", "trans": ["到达"]},
    {"name": "arrive at/in", "trans": ["到达"]}, {"name": "can't wait to do", "trans": ["迫不及待做某事"]},
    {"name": "get off", "trans": ["下车"]}, {"name": "interest", "trans": ["令人感兴趣的事或人；兴趣"]},
    {"name": "place of interest", "trans": ["景点"]}, {"name": "main", "trans": ["主要的"]},
    {"name": "sights", "trans": ["名胜，风景"]}, {"name": "culture", "trans": ["文化"]},
    {"name": "Internet", "trans": ["网络"]}, {"name": "page", "trans": ["页，页面，页码"]},
    {"name": "home page", "trans": ["主页"]}, {"name": "yourselves", "trans": ["你们自己"]},
    {"name": "themselves", "trans": ["他们自己"]}, {"name": "by oneself", "trans": ["独立地，独自"]},
    {"name": "itself", "trans": ["它自己"]}, {"name": "pull", "trans": ["拉，拖，移开"]},
    {"name": "rock", "trans": ["岩石"]}, {"name": "luckily", "trans": ["幸好，幸运的是"]},
    {"name": "climber", "trans": ["登山者，攀爬者"]}, {"name": "final", "trans": ["决赛"]},
    {"name": "support", "trans": ["支持"]}, {"name": "take place", "trans": ["进行，发生"]},
    {"name": "cheer", "trans": ["欢呼，喝彩"]}, {"name": "reach", "trans": ["到达"]},
    {"name": "half-time", "trans": ["中场休息"]}, {"name": "get on", "trans": ["上车"]},
    {"name": "cost", "trans": ["费用，价钱"]}, {"name": "rest", "trans": ["休息，歇息"]},
    {"name": "free", "trans": ["免费的"]}, {"name": "helpless", "trans": ["无助的"]},
    {"name": "useful", "trans": ["有用的，有益的"]}, {"name": "useless", "trans": ["无用的"]},
    {"name": "cheerful", "trans": ["兴高采烈的"]}, {"name": "colourful", "trans": ["多彩的"]},
    {"name": "ticket", "trans": ["票，入场券"]}, {"name": "keep", "trans": ["留着，不退还"]},
    {"name": "square", "trans": ["广场"]}, {"name": "instruction", "trans": ["指示，用法说明"]},
    {"name": "had better", "trans": ["最好"]}, {"name": "tool", "trans": ["工具"]},
    {"name": "brush", "trans": ["刷子，画笔"]}, {"name": "glue", "trans": ["胶水"]},
    {"name": "rope", "trans": ["绳索"]}, {"name": "scissors", "trans": ["剪刀"]},
    {"name": "tape", "trans": ["胶带，磁带"]}, {"name": "DIY", "trans": ["自己动手做"]},
    {"name": "exactly", "trans": ["确切地，精确地"]}, {"name": "stand for", "trans": ["代表，象征"]},
    {"name": "repair", "trans": ["修补"]}, {"name": "decorate", "trans": ["装饰"]},
    {"name": "instead of", "trans": ["而不是，代替"]}, {"name": "rose", "trans": ["玫瑰花"]},
    {"name": "crazy", "trans": ["着迷的，狂热的，发疯的"]}, {"name": "be crazy about", "trans": ["对…着迷的"]},
    {"name": "terrible", "trans": ["可怕的"]}, {"name": "once", "trans": ["曾经，一度"]},
    {"name": "put in", "trans": ["安装"]}, {"name": "mistake", "trans": ["错误，失误"]},
    {"name": "make a mistake", "trans": ["犯错误"]}, {"name": "power cut", "trans": ["供电中断，停电"]},
    {"name": "pipe", "trans": ["管子，水管"]}, {"name": "fill", "trans": ["使充满"]},
    {"name": "fill...with", "trans": ["用…充满"]}, {"name": "ceiling", "trans": ["天花板"]},
    {"name": "shelf", "trans": ["架子，搁板"]}, {"name": "advise", "trans": ["建议，忠告，劝告"]},
    {"name": "course", "trans": ["课程，过程"]}, {"name": "already", "trans": ["已经"]},
    {"name": "instead", "trans": ["反而，却"]}, {"name": "attend", "trans": ["经常去，出席"]},
    {"name": "cut", "trans": ["剪下，切下，割下"]}, {"name": "sentence", "trans": ["句子"]},
    {"name": "grape", "trans": ["葡萄"]}, {"name": "strawberry", "trans": ["草莓"]},
    {"name": "spoon", "trans": ["调羹"]}, {"name": "salad", "trans": ["沙拉"]},
    {"name": "cream", "trans": ["奶油，乳脂，霜"]}, {"name": "mix", "trans": ["混合"]},
    {"name": "add", "trans": ["增加，补充"]}, {"name": "tip", "trans": ["提示，指点"]},
    {"name": "example", "trans": ["例子，榜样"]}, {"name": "for example", "trans": ["例如"]},
    {"name": "leave", "trans": ["使处于某种状态"]}, {"name": "sauce", "trans": ["调味汁，酱"]},
    {"name": "ham", "trans": ["火腿"]}, {"name": "correct", "trans": ["正确的"]},
    {"name": "finished", "trans": ["完成的"]}, {"name": "certain", "trans": ["确定的"]},
    {"name": "active", "trans": ["积极的，活跃的，主动的"]}, {"name": "possible", "trans": ["可能的"]},
    {"name": "tidy up", "trans": ["收拾妥，整理好"]}, {"name": "secret", "trans": ["秘密的"]},
    {"name": "wrong", "trans": ["错误地，不对"]}, {"name": "go wrong", "trans": ["犯错；出故障"]},
    {"name": "spell", "trans": ["拼写"]}, {"name": "cut out", "trans": ["剪出"]},
    {"name": "balloon", "trans": ["气球"]}, {"name": "stick", "trans": ["粘住，钉住"]},
    {"name": "cover", "trans": ["封面，盖子，罩"]}, {"name": "complete", "trans": ["完成"]},
    {"name": "paint", "trans": ["颜料"]}, {"name": "furniture", "trans": ["家具"]},
    {"name": "wild", "trans": ["野生的；自然环境，野生状态"]}, {"name": "free", "trans": ["自由的，不受束缚的"]},
    {"name": "dish", "trans": ["一道菜；盘，碟"]}, {"name": "no way", "trans": ["不可能"]},
    {"name": "pity", "trans": ["同情"]}, {"name": "have/take pity on", "trans": ["同情，怜悯"]},
    {"name": "die", "trans": ["死"]}, {"name": "in fact", "trans": ["实际上，事实上"]},
    {"name": "dolphin", "trans": ["海豚"]}, {"name": "giant panda", "trans": ["大熊猫"]},
    {"name": "squirrel", "trans": ["松鼠"]}, {"name": "zebra", "trans": ["斑马"]},
    {"name": "mean", "trans": ["意思是，意味着"]}, {"name": "be born", "trans": ["出生"]},
    {"name": "beginning", "trans": ["开始，起初"]}, {"name": "in the beginning", "trans": ["一开始"]},
    {"name": "sadly", "trans": ["令人遗憾地，不幸地，伤心地"]}, {"name": "face", "trans": ["面临，面对"]},
    {"name": "serious", "trans": ["严重的"]}, {"name": "live on", "trans": ["以食…为生"]},
    {"name": "mainly", "trans": ["主要地，大部分"]}, {"name": "however", "trans": ["然而"]},
    {"name": "result", "trans": ["结果"]}, {"name": "as a result", "trans": ["因此"]},
    {"name": "danger", "trans": ["危险"]}, {"name": "in danger", "trans": ["处境危险"]},
    {"name": "action", "trans": ["行动，行为"]}, {"name": "take action", "trans": ["采取行动"]},
    {"name": "right away", "trans": ["立刻，马上"]}, {"name": "reserve", "trans": ["保护区"]},
    {"name": "law", "trans": ["法律，法规"]}, {"name": "none", "trans": ["没有一个"]},
    {"name": "at birth", "trans": ["出生时，诞生时"]}, {"name": "closed", "trans": ["关闭的"]},
    {"name": "bat", "trans": ["蝙蝠"]}, {"name": "bee", "trans": ["蜜蜂"]},
    {"name": "lost", "trans": ["迷路的，迷失的"]}, {"name": "get lost", "trans": ["迷路"]},
    {"name": "the same as", "trans": ["与…同样"]}, {"name": "save", "trans": ["储存，节省"]},
    {"name": "stripe", "trans": ["条纹"]}, {"name": "while", "trans": ["一会儿，一段时间"]},
    {"name": "quality", "trans": ["特性，才能"]}, {"name": "hunter", "trans": ["猎人"]},
    {"name": "catch", "trans": ["捉住，捕获"]}, {"name": "wolf", "trans": ["狼"]},
    {"name": "thick", "trans": ["厚的，密的，浓的"]}, {"name": "lose", "trans": ["失去，被…夺去，输掉"]},
    {"name": "living", "trans": ["生存，生计"]}, {"name": "kill", "trans": ["杀死"]},
    {"name": "human", "trans": ["人"]}, {"name": "yours sincerely", "trans": ["你的真诚的"]},
    {"name": "sorry", "trans": ["难过的，遗憾的"]}, {"name": "pity", "trans": ["遗憾，可惜"]},
    {"name": "sell", "trans": ["卖，出售"]}, {"name": "shame", "trans": ["憾事，羞愧"]},
    {"name": "act", "trans": ["行动；表演"]}, {"name": "illness", "trans": ["疾病"]},
    {"name": "because of", "trans": ["因为，由于"]}, {"name": "accept", "trans": ["接受，收受"]},
    {"name": "report", "trans": ["报告"]}, {"name": "tail", "trans": ["尾巴"]},
    {"name": "insect", "trans": ["昆虫"]}, {"name": "move", "trans": ["活动，移动，搬迁"]},
    {"name": "slowly", "trans": ["缓慢地"]}, {"name": "daytime", "trans": ["白天"]},
    {"name": "otherwise", "trans": ["要不然，否则"]}, {"name": "birdwatching", "trans": ["观鸟"]},
    {"name": "market", "trans": ["市场"]}, {"name": "yeah", "trans": ["是的"]},
    {"name": "hen", "trans": ["母鸡"]}, {"name": "yummy", "trans": ["美味的，可口的"]},
    {"name": "crane", "trans": ["鹤"]}, {"name": "sparrow", "trans": ["麻雀"]},
    {"name": "feather", "trans": ["羽毛"]}, {"name": "swan", "trans": ["天鹅"]},
    {"name": "eagle", "trans": ["鹰"]}, {"name": "broad", "trans": ["宽的，宽大的"]},
    {"name": "wing", "trans": ["翅膀"]}, {"name": "type", "trans": ["种类"]},
    {"name": "rare", "trans": ["罕见的，稀有的"]}, {"name": "nature", "trans": ["大自然，自然界"]},
    {"name": "wetland", "trans": ["湿地"]}, {"name": "provide", "trans": ["提供"]},
    {"name": "cover", "trans": ["庇护所"]}, {"name": "wildlife", "trans": ["野生动物"]},
    {"name": "perfect", "trans": ["极好的，完美的"]}, {"name": "round", "trans": ["周围，绕一圈"]},
    {"name": "all year round", "trans": ["一年到头"]}, {"name": "while", "trans": ["然而"]},
    {"name": "stay", "trans": ["停留，逗留"]}, {"name": "easily", "trans": ["容易地，不费力地"]},
    {"name": "cent", "trans": ["分，分币"]}, {"name": "per cent", "trans": ["百分之…"]},
    {"name": "in order to", "trans": ["以便，为的是"]}, {"name": "space", "trans": ["空间"]},
    {"name": "lead", "trans": ["领导，带领"]}, {"name": "lead to", "trans": ["导致"]},
    {"name": "less and less", "trans": ["越来越少"]}, {"name": "moreover", "trans": ["此外"]},
    {"name": "fisherman", "trans": ["渔民，钓鱼的人"]}, {"name": "fish", "trans": ["捕鱼，钓鱼"]},
    {"name": "government", "trans": ["政府"]}, {"name": "prevent", "trans": ["防止，预防"]},
    {"name": "society", "trans": ["协会，社会"]}, {"name": "record", "trans": ["记录"]},
    {"name": "change", "trans": ["改变，变化"]}, {"name": "tourist", "trans": ["旅行者，观光者"]},
    {"name": "count", "trans": ["计算清点总数；数数"]}, {"name": "describe", "trans": ["描述"]},
    {"name": "understand", "trans": ["理解，明白"]}, {"name": "importance", "trans": ["重要性"]},
    {"name": "write down", "trans": ["写下，记下"]}, {"name": "cover", "trans": ["覆盖，包括"]},
    {"name": "red-crowned crane", "trans": ["丹顶鹤"]}, {"name": "binoculars", "trans": ["望远镜"]},
    {"name": "clearly", "trans": ["清晰地"]}, {"name": "speaker", "trans": ["说话人，演讲者"]},
    {"name": "tour", "trans": ["旅行"]}, {"name": "application", "trans": ["申请"]},
    {"name": "form", "trans": ["表格"]}, {"name": "address", "trans": ["地址"]},
    {"name": "chairperson", "trans": ["主席"]}, {"name": "introduce", "trans": ["介绍"]},
    {"name": "natural", "trans": ["自然的，天然的"]}, {"name": "bet", "trans": ["打赌；敢说"]},
    {"name": "foggy", "trans": ["有雾的，多雾的"]}, {"name": "rainy", "trans": ["有雨的"]},
    {"name": "snowy", "trans": ["有雪的"]}, {"name": "butterfly", "trans": ["蝴蝶"]},
    {"name": "shower", "trans": ["阵雨，阵雪"]}, {"name": "memory", "trans": ["记忆，回忆"]},
    {"name": "stream", "trans": ["小河，溪流"]}, {"name": "shade", "trans": ["阴凉处，树荫处"]},
    {"name": "pile", "trans": ["堆"]}, {"name": "upon", "trans": ["在…之上"]},
    {"name": "harvest", "trans": ["收割，收获"]}, {"name": "crop", "trans": ["庄稼，收成"]},
    {"name": "as", "trans": ["当…时，随着"]}, {"name": "temperature", "trans": ["温度"]},
    {"name": "drop", "trans": ["下降，落下"]}, {"name": "rise", "trans": ["上升，升起"]},
    {"name": "cloud", "trans": ["云"]}, {"name": "kick", "trans": ["踢"]},
    {"name": "fever", "trans": ["发烧"]}, {"name": "cough", "trans": ["咳嗽"]},
    {"name": "awful", "trans": ["糟糕的，很坏的"]}, {"name": "snowstorm", "trans": ["暴风雪"]},
    {"name": "wind", "trans": ["风"]}, {"name": "around", "trans": ["大约"]},
    {"name": "sunshine", "trans": ["阳光"]}, {"name": "rest", "trans": ["其余的部分"]},
    {"name": "degree", "trans": ["度数"]}, {"name": "bit", "trans": ["一点，少量"]},
    {"name": "a bit", "trans": ["有一点"]}, {"name": "blow", "trans": ["吹；刮"]},
    {"name": "loudly", "trans": ["大声地"]}, {"name": "ring", "trans": ["给…打电话；响起铃声"]},
    {"name": "fog", "trans": ["雾"]}, {"name": "sleepy", "trans": ["困倦的，瞌睡的"]},
    {"name": "shine", "trans": ["光亮，光泽"]}, {"name": "shiny", "trans": ["光亮的，反光的"]},
    {"name": "sudden", "trans": ["突然的"]}, {"name": "snowball", "trans": ["雪球"]},
    {"name": "fight", "trans": ["打仗"]}, {"name": "deep", "trans": ["深的"]},
    {"name": "frozen", "trans": ["结冰的"]}, {"name": "land", "trans": ["陆地"]},
    {"name": "exciting", "trans": ["激动人心的"]}, {"name": "throw", "trans": ["扔，投"]},
    {"name": "scream", "trans": ["尖叫，惊呼"]}, {"name": "snowman", "trans": ["雪人"]},
    {"name": "ice", "trans": ["冰"]}, {"name": "everywhere", "trans": ["到处"]},
    {"name": "disaster", "trans": ["灾难，不幸，祸患"]}, {"name": "mop", "trans": ["用拖把擦干净"]},
    {"name": "up", "trans": ["完全地"]}, {"name": "earthquake", "trans": ["地震"]},
    {"name": "thousands of", "trans": ["成千上万的"]}, {"name": "accident", "trans": ["事故，意外的事"]},
    {"name": "coach", "trans": ["长途汽车"]}, {"name": "crash", "trans": ["猛撞，碰撞"]},
    {"name": "flood", "trans": ["洪水，水灾"]}, {"name": "wash away", "trans": ["冲走"]},
    {"name": "village", "trans": ["村庄，乡村"]}, {"name": "lightning", "trans": ["闪电"]},
    {"name": "storm", "trans": ["风暴，暴风雨"]}, {"name": "thunder", "trans": ["雷声，雷"]},
    {"name": "catch fire", "trans": ["着火"]}, {"name": "slight", "trans": ["轻微的"]},
    {"name": "shake", "trans": ["摇动，震动"]}, {"name": "loud", "trans": ["响亮的，大声的"]},
    {"name": "bomb", "trans": ["炸弹"]}, {"name": "fear", "trans": ["害怕，恐惧"]},
    {"name": "direction", "trans": ["方向"]}, {"name": "in all directions", "trans": ["四面八方"]},
    {"name": "brick", "trans": ["砖，砖块"]}, {"name": "collapse", "trans": ["崩塌，坍塌"]},
    {"name": "silent", "trans": ["寂静的"]}, {"name": "not at all", "trans": ["一点也不是"]},
    {"name": "nervous", "trans": ["紧张的"]}, {"name": "heart", "trans": ["心脏"]},
    {"name": "beat", "trans": ["跳动"]}, {"name": "trapped", "trans": ["困住的"]},
    {"name": "mind", "trans": ["头脑"]}, {"name": "calm", "trans": ["使平静，使镇定"]},
    {"name": "calm down", "trans": ["冷静"]}, {"name": "since", "trans": ["由于，既然"]},
    {"name": "alive", "trans": ["仍然活着的"]}, {"name": "darkness", "trans": ["黑暗"]},
    {"name": "find one's way out", "trans": ["找到出路"]}, {"name": "shout", "trans": ["呼喊，喊叫声"]},
    {"name": "finally", "trans": ["最后，终于"]}, {"name": "daylight", "trans": ["日光"]},
    {"name": "safe", "trans": ["安全的"]}, {"name": "asleep", "trans": ["睡着的"]},
    {"name": "after", "trans": ["在…以后"]}, {"name": "break", "trans": ["损坏；打破"]},
    {"name": "break down", "trans": ["出故障，坏掉"]}, {"name": "because of", "trans": ["因为，由"]},
    {"name": "sound", "trans": ["健康的，无损伤的"]}, {"name": "safe and sound", "trans": ["安然无恙"]},
    {"name": "emergency", "trans": ["紧急情况"]}, {"name": "situation", "trans": ["情况"]},
    {"name": "heating", "trans": ["供暖"]}, {"name": "homeless", "trans": ["无家可归的"]},
    {"name": "typhoon", "trans": ["台风"]}, {"name": "terrible", "trans": ["可怕的"]},
    {"name": "state", "trans": ["状态，情况"]}, {"name": "traffic", "trans": ["交通"]},
    {"name": "fireman", "trans": ["消防员"]}, {"name": "in fear", "trans": ["恐惧地，害怕地"]},
    {"name": "say to oneself", "trans": ["暗想；自言自语"]}, {"name": "weak", "trans": ["虚弱的"]},
    {"name": "voice", "trans": ["嗓音，说话声"]}, {"name": "except", "trans": ["除…之外"]},
    {"name": "smoke", "trans": ["烟"]}, {"name": "burn", "trans": ["着火"]},
    {"name": "put out", "trans": ["扑灭，熄灭"]}, {"name": "heavily", "trans": ["大量地"]},
    {"name": "guess", "trans": ["猜测，估计"]}, {"name": "hat", "trans": ["帽子"]},
    {"name": "clear", "trans": ["清除，清理"]}, {"name": "policeman", "trans": ["警察"]},
    {"name": "ache", "trans": ["疼痛"]}, {"name": "postman", "trans": ["邮递员"]},
    {"name": "airport", "trans": ["机场"]}, {"name": "passport", "trans": ["护照"]},
    {"name": "close", "trans": ["差一点儿，险些"]}, {"name": "report", "trans": ["报道；汇报"]},
    {"name": "bush fire", "trans": ["山林大火"]}, {"name": "so far", "trans": ["迄今为止"]},
    {"name": "including", "trans": ["包括…在内"]}, {"name": "sign", "trans": ["标牌，指示牌"]},
    {"name": "avoid", "trans": ["避免"]}, {"name": "wound", "trans": ["伤口"]},
]

GRADE_8_LOWER = [
    {"name": "past", "trans": ["过去"]}, {"name": "present", "trans": ["现在，目前"]},
    {"name": "just", "trans": ["刚才"]}, {"name": "used to", "trans": ["曾经"]},
    {"name": "since", "trans": ["自……以来"]}, {"name": "ever", "trans": ["曾经"]},
    {"name": "northern", "trans": ["北方的，北部的"]}, {"name": "married", "trans": ["已婚的，结婚的"]},
    {"name": "wife", "trans": ["妻子"]}, {"name": "block", "trans": ["街区"]},
    {"name": "pollution", "trans": ["污染；污染物"]}, {"name": "factory", "trans": ["工厂"]},
    {"name": "waste", "trans": ["废料，废品"]}, {"name": "realize", "trans": ["意识到；实现"]},
    {"name": "improve", "trans": ["改进，改善"]}, {"name": "situation", "trans": ["形势，情况"]},
    {"name": "impossible", "trans": ["不可能的"]}, {"name": "lonely", "trans": ["孤独的，寂寞的"]},
    {"name": "husband", "trans": ["丈夫"]}, {"name": "interview", "trans": ["采访；会见"]},
    {"name": "abroad", "trans": ["到（在）国外"]}, {"name": "primary", "trans": ["小学教育的；初级的"]},
    {"name": "communicate", "trans": ["交流，交际"]}, {"name": "communication", "trans": ["交流，交际"]},
    {"name": "exactly", "trans": ["正是，没错"]}, {"name": "be used to", "trans": ["习惯于，适应于"]},
    {"name": "narrow", "trans": ["狭窄的"]}, {"name": "open space", "trans": ["开阔的空地"]},
    {"name": "environment", "trans": ["环境"]}, {"name": "transport", "trans": ["交通车辆，运输工具"]},
    {"name": "travelling", "trans": ["旅行"]}, {"name": "hey", "trans": ["嘿，喂"]},
    {"name": "miss", "trans": ["想念，思念"]}, {"name": "fantastic", "trans": ["极好的，美妙的"]},
    {"name": "indoor", "trans": ["（在）室内的"]}, {"name": "roller coaster", "trans": ["过山车"]},
    {"name": "speed", "trans": ["速度"]}, {"name": "ride", "trans": ["乘坐游乐设施"]},
    {"name": "cartoon", "trans": ["卡通片，动画片"]}, {"name": "character", "trans": ["人物"]},
    {"name": "such", "trans": ["这样的"]}, {"name": "such as", "trans": ["例如"]},
    {"name": "parade", "trans": ["庆祝游行"]}, {"name": "magic", "trans": ["魔法"]},
    {"name": "pie", "trans": ["派，馅饼"]}, {"name": "feel", "trans": ["感觉到，意识到"]},
    {"name": "couple", "trans": ["一对；几个，几件"]}, {"name": "castle", "trans": ["城堡"]},
    {"name": "sand", "trans": ["沙；沙滩"]}, {"name": "marry", "trans": ["结婚，嫁，娶"]},
    {"name": "dead", "trans": ["死的"]}, {"name": "beauty", "trans": ["美丽；美人"]},
    {"name": "seaside", "trans": ["海边的"]}, {"name": "theme park", "trans": ["主题公园"]},
    {"name": "sailing", "trans": ["帆船运动，航行"]}, {"name": "except", "trans": ["除了……以外"]},
    {"name": "view", "trans": ["景色，风景"]}, {"name": "mountain", "trans": ["高山"]},
    {"name": "business", "trans": ["公事；商业；生意"]}, {"name": "direct", "trans": ["直达的，直接的"]},
    {"name": "flight", "trans": ["航班；航行"]}, {"name": "delicious", "trans": ["美味的，可口的"]},
    {"name": "seafood", "trans": ["海鲜"]}, {"name": "airport", "trans": ["机场"]},
    {"name": "relative", "trans": ["亲戚"]}, {"name": "online", "trans": ["联网的，在线的"]},
    {"name": "programme", "trans": ["节目；计划，方案"]}, {"name": "remote control", "trans": ["遥控器"]},
    {"name": "channel", "trans": ["频道"]}, {"name": "keyboard", "trans": ["键盘"]},
    {"name": "unit", "trans": ["机件；单位"]}, {"name": "mouse", "trans": ["鼠标"]},
    {"name": "screen", "trans": ["显示屏，屏幕"]}, {"name": "receive", "trans": ["收到，接到"]},
    {"name": "guide", "trans": ["导游，向导"]}, {"name": "icon", "trans": ["图标"]},
    {"name": "click", "trans": ["点击"]}, {"name": "Asia", "trans": ["亚洲"]},
    {"name": "Africa", "trans": ["非洲"]}, {"name": "Europe", "trans": ["欧洲"]},
    {"name": "America", "trans": ["美洲"]}, {"name": "world-famous", "trans": ["世界著名的，举世闻名的"]},
    {"name": "trade", "trans": ["贸易"]}, {"name": "southern", "trans": ["南方的，南部的"]},
    {"name": "international", "trans": ["国际的"]}, {"name": "gather", "trans": ["聚集，集合"]},
    {"name": "huge", "trans": ["巨大的"]}, {"name": "darkness", "trans": ["黑暗"]},
    {"name": "island", "trans": ["岛屿"]}, {"name": "several", "trans": ["几个，数个"]},
    {"name": "lawn", "trans": ["草坪"]}, {"name": "relax", "trans": ["放松，休息"]},
    {"name": "musical", "trans": ["音乐剧"]}, {"name": "website", "trans": ["网站"]},
    {"name": "passport", "trans": ["护照"]}, {"name": "coast", "trans": ["海岸"]},
    {"name": "mind", "trans": ["介意"]}, {"name": "print", "trans": ["打印；印刷"]},
    {"name": "pleasure", "trans": ["高兴，乐意"]}, {"name": "book", "trans": ["预订，订"]},
    {"name": "queen", "trans": ["女王"]}, {"name": "ruler", "trans": ["统治者；管理者"]},
    {"name": "pound", "trans": ["英镑"]}, {"name": "consist of", "trans": ["由……组成"]},
    {"name": "European", "trans": ["欧洲的"]}, {"name": "dollar", "trans": ["美元"]},
    {"name": "read", "trans": ["读物"]}, {"name": "cooking", "trans": ["烹饪，烹调"]},
    {"name": "novel", "trans": ["小说"]}, {"name": "Germany", "trans": ["德国"]},
    {"name": "knowledge", "trans": ["知识"]}, {"name": "spare", "trans": ["空闲的；多余的"]},
    {"name": "French", "trans": ["法国（人）的"]}, {"name": "writer", "trans": ["作者，作家"]},
    {"name": "ugly", "trans": ["丑陋的"]}, {"name": "against", "trans": ["紧靠，碰，撞"]},
    {"name": "tie", "trans": ["捆，绑"]}, {"name": "stomach", "trans": ["腹部；胃"]},
    {"name": "until", "trans": ["直到……为止"]}, {"name": "finger", "trans": ["手指"]},
    {"name": "tiny", "trans": ["极小的"]}, {"name": "continue", "trans": ["继续"]},
    {"name": "either", "trans": ["也"]}, {"name": "manage", "trans": ["设法完成；管理"]},
    {"name": "lift", "trans": ["举起，抬高；提高"]}, {"name": "army", "trans": ["大批，大群"]},
    {"name": "must", "trans": ["应该，必须；一定"]}, {"name": "unable", "trans": ["不能的，不会的"]},
    {"name": "shoulder", "trans": ["肩膀"]}, {"name": "hand", "trans": ["交；递，给"]},
    {"name": "return", "trans": ["归还"]}, {"name": "renew", "trans": ["续借；更新"]},
    {"name": "series", "trans": ["一系列；系列节目"]}, {"name": "publish", "trans": ["出版"]},
    {"name": "success", "trans": ["成功"]}, {"name": "translate", "trans": ["翻译"]},
    {"name": "copy", "trans": ["一本（份，册）；副本"]}, {"name": "Canadian", "trans": ["加拿大（人）的"]},
    {"name": "confidence", "trans": ["信心"]}, {"name": "experience", "trans": ["经历，经验"]},
    {"name": "advice", "trans": ["建议，忠告，劝告"]}, {"name": "librarian", "trans": ["图书管理员"]},
    {"name": "habit", "trans": ["习惯"]}, {"name": "classical", "trans": ["古典的"]},
    {"name": "opposite", "trans": ["在……对面；与……相反"]}, {"name": "open up", "trans": ["开启；开创；开辟"]},
    {"name": "manners", "trans": ["礼貌，礼仪；规矩"]}, {"name": "cut in", "trans": ["打断（谈话），插嘴"]},
    {"name": "politely", "trans": ["礼貌地"]}, {"name": "litter", "trans": ["垃圾，杂物"]},
    {"name": "tap", "trans": ["水龙头；旋塞"]}, {"name": "flow", "trans": ["流动"]},
    {"name": "pick", "trans": ["采，摘"]}, {"name": "obey", "trans": ["遵守，顺从"]},
    {"name": "queue", "trans": ["排队等候"]}, {"name": "turn", "trans": ["轮流，（轮流的）顺序"]},
    {"name": "proper", "trans": ["符合习俗的；正确的"]}, {"name": "greet", "trans": ["问候，打招呼"]},
    {"name": "kiss", "trans": ["亲吻"]}, {"name": "close", "trans": ["亲密的；严密的"]},
    {"name": "conversation", "trans": ["（非正式）交谈，谈话"]}, {"name": "avoid", "trans": ["避免"]},
    {"name": "subject", "trans": ["话题；主题"]}, {"name": "behave", "trans": ["表现"]},
    {"name": "public", "trans": ["民众，群体"]}, {"name": "push", "trans": ["推，挤"]},
    {"name": "bump", "trans": ["撞，碰"]}, {"name": "touch", "trans": ["触摸，碰"]},
    {"name": "excuse", "trans": ["原谅，宽恕"]}, {"name": "loud", "trans": ["大声地"]},
    {"name": "saying", "trans": ["谚语，格言"]}, {"name": "Roman", "trans": ["罗马人"]},
    {"name": "discussion", "trans": ["讨论"]}, {"name": "express", "trans": ["表达"]},
    {"name": "explain", "trans": ["解释"]}, {"name": "warn", "trans": ["警告，告诫"]},
    {"name": "successful", "trans": ["成功的"]}, {"name": "shortly after", "trans": ["不久以后"]},
    {"name": "pain", "trans": ["痛，疼痛"]}, {"name": "practice", "trans": ["练习；训练；实践"]},
    {"name": "purpose", "trans": ["目的"]}, {"name": "guest", "trans": ["客人，宾客"]},
    {"name": "host", "trans": ["主人；主持"]}, {"name": "impolite", "trans": ["不礼貌的"]},
    {"name": "train", "trans": ["接受训练；培训，训练"]}, {"name": "Olympics", "trans": ["奥林匹克运动会"]},
    {"name": "support", "trans": ["支持"]}, {"name": "meaningful", "trans": ["有意义的"]},
    {"name": "blind", "trans": ["瞎的"]}, {"name": "deaf", "trans": ["聋的"]},
    {"name": "disabled", "trans": ["残疾的"]}, {"name": "elderly", "trans": ["年老的"]},
    {"name": "homeless", "trans": ["无家可归的"]}, {"name": "volunteer", "trans": ["志愿做，义务做"]},
    {"name": "expect", "trans": ["期待，指望；预料"]}, {"name": "adult", "trans": ["成年人"]},
    {"name": "intellectual", "trans": ["智力的"]}, {"name": "disability", "trans": ["缺陷，障碍"]},
    {"name": "chance", "trans": ["机会"]}, {"name": "event", "trans": ["运动比赛项目；大事"]},
    {"name": "similar", "trans": ["同样的，类似的"]}, {"name": "necessary", "trans": ["必须的，必要的"]},
    {"name": "training", "trans": ["培训，训练"]}, {"name": "task", "trans": ["任务，工作"]},
    {"name": "athlete", "trans": ["运动员"]}, {"name": "coach", "trans": ["教练"]},
    {"name": "gold", "trans": ["黄金；金牌"]}, {"name": "silver", "trans": ["银；银牌"]},
    {"name": "confident", "trans": ["自信的"]}, {"name": "background", "trans": ["背景"]},
    {"name": "achieve", "trans": ["实现，达到"]}, {"name": "prize", "trans": ["奖赏，奖品"]},
    {"name": "donate", "trans": ["捐献"]}, {"name": "charity", "trans": ["慈善；慈善机构"]},
    {"name": "organization", "trans": ["机构，组织"]}, {"name": "blood", "trans": ["血"]},
    {"name": "southwest", "trans": ["西南方"]}, {"name": "northwest", "trans": ["西北方"]},
    {"name": "project", "trans": ["项目；课题"]}, {"name": "disease", "trans": ["疾病"]},
    {"name": "operation", "trans": ["手术"]}, {"name": "survivor", "trans": ["幸存者"]},
    {"name": "introduction", "trans": ["引言；介绍"]}, {"name": "especially", "trans": ["特别，尤其"]},
    {"name": "basic", "trans": ["基础的，基本的"]}, {"name": "education", "trans": ["教育"]},
    {"name": "equal", "trans": ["平等的"]}, {"name": "right", "trans": ["权利"]},
    {"name": "spread", "trans": ["扩散；展开"]}, {"name": "interviewer", "trans": ["采访者"]},
    {"name": "blindness", "trans": ["失明"]}, {"name": "mostly", "trans": ["主要地，大部分地"]},
    {"name": "case", "trans": ["病例；案例"]}, {"name": "cure", "trans": ["治愈"]},
    {"name": "medical", "trans": ["医学的，医疗的"]}, {"name": "treatment", "trans": ["治疗"]},
    {"name": "patient", "trans": ["病人"]}, {"name": "afford", "trans": ["买得起；能做"]},
    {"name": "proud", "trans": ["自豪的，骄傲的"]}, {"name": "medicine", "trans": ["医学；药"]},
    {"name": "development", "trans": ["发展；加强"]}, {"name": "leaflet", "trans": ["传单；散页印刷品"]},
    {"name": "hand out", "trans": ["分发"]}, {"name": "set up", "trans": ["建立，建起"]},
    {"name": "include", "trans": ["包含，包括"]}, {"name": "war", "trans": ["战争"]},
    {"name": "organize", "trans": ["组织"]}, {"name": "pale", "trans": ["苍白的"]},
    {"name": "matter", "trans": ["事情，问题"]}, {"name": "check", "trans": ["检查"]},
    {"name": "secretary", "trans": ["秘书"]}, {"name": "decide", "trans": ["决定"]},
    {"name": "India", "trans": ["印度"]}, {"name": "officer", "trans": ["官员"]},
    {"name": "dig", "trans": ["挖（洞，沟等）"]}, {"name": "serious", "trans": ["认真的，严肃的"]},
    {"name": "reduce", "trans": ["减少，降低"]}, {"name": "switch off", "trans": ["关上（开关）"]},
    {"name": "recycle", "trans": ["回收利用，循环利用"]}, {"name": "cause", "trans": ["导致；造成"]},
    {"name": "wise", "trans": ["明智的，充满智慧的"]}, {"name": "plastic", "trans": ["塑料"]},
    {"name": "separate", "trans": ["分开，隔开"]}, {"name": "allow", "trans": ["允许"]},
    {"name": "cut down", "trans": ["砍倒"]}, {"name": "punish", "trans": ["处罚，惩罚"]},
    {"name": "fine", "trans": ["罚款"]}, {"name": "limit", "trans": ["限制"]},
    {"name": "depend on", "trans": ["依靠，依赖；取决于"]}, {"name": "rich", "trans": ["丰富的；富有的"]},
    {"name": "soil", "trans": ["土壤"]}, {"name": "chemical", "trans": ["化学的；化学制品"]},
    {"name": "truck", "trans": ["卡车；载重汽车"]}, {"name": "fuel", "trans": ["燃料"]},
    {"name": "pour", "trans": ["倾倒，倒出；倾泻"]}, {"name": "air conditioning", "trans": ["空调调节系统"]},
    {"name": "environmentally friendly", "trans": ["环保的"]}, {"name": "separate...into", "trans": ["把……分成"]},
    {"name": "wisely", "trans": ["明智地"]}, {"name": "run out", "trans": ["用完，耗尽"]},
    {"name": "resource", "trans": ["资源"]}, {"name": "electricity", "trans": ["电，电能"]},
    {"name": "electronic", "trans": ["电子的"]},
]

GRADE_9_UPPER = [
    {"name": "eat up", "trans": ["吃光，吃完"]}, {"name": "creative", "trans": ["有创造力的，创造性的"]},
    {"name": "curious", "trans": ["好奇的"]}, {"name": "energetic", "trans": ["精力充沛的"]},
    {"name": "modest", "trans": ["谦虚的"]}, {"name": "organized", "trans": ["有条理的，有效率的"]},
    {"name": "order", "trans": ["顺序"]}, {"name": "keep in order", "trans": ["使……保持井然有序"]},
    {"name": "show off", "trans": ["炫耀"]}, {"name": "grammar", "trans": ["语法"]},
    {"name": "come up with", "trans": ["想出（主意）"]}, {"name": "neither", "trans": ["（两者）都不"]},
    {"name": "nor", "trans": ["也不"]}, {"name": "neither...nor...", "trans": ["既不……也不……"]},
    {"name": "accountant", "trans": ["会计"]}, {"name": "born", "trans": ["天生的"]},
    {"name": "impress", "trans": ["给……留下印象"]}, {"name": "sculpture", "trans": ["雕塑，雕像"]},
    {"name": "praise", "trans": ["赞扬，表扬"]}, {"name": "sales department", "trans": ["销售部"]},
    {"name": "general", "trans": ["总的，普遍的，首席的"]}, {"name": "race", "trans": ["竞赛，赛跑"]},
    {"name": "either...or...", "trans": ["不是……就是……"]}, {"name": "lead", "trans": ["领先地位，榜样"]},
    {"name": "take the lead", "trans": ["处于领先地位"]}, {"name": "fall behind", "trans": ["落后"]},
    {"name": "challenge", "trans": ["挑战"]}, {"name": "chief", "trans": ["主要的，首要的"]},
    {"name": "high-speed", "trans": ["高速的"]}, {"name": "connect", "trans": ["连接"]},
    {"name": "connect to/with", "trans": ["与……相连，连接"]}, {"name": "miss", "trans": ["错误，过失"]},
    {"name": "as good as", "trans": ["和……几乎一样，简直是"]}, {"name": "attention", "trans": ["注意，专心"]},
    {"name": "pay attention to", "trans": ["注意"]}, {"name": "standard", "trans": ["标准"]},
    {"name": "pioneer", "trans": ["先锋，开拓者"]}, {"name": "surgeon", "trans": ["外科大夫"]},
    {"name": "carelessness", "trans": ["粗心"]}, {"name": "extra", "trans": ["额外的，附加的"]},
    {"name": "devote", "trans": ["把……贡献，把……专用于"]}, {"name": "respect", "trans": ["尊敬，尊重"]},
    {"name": "suitable", "trans": ["合适的，适宜的"]}, {"name": "partner", "trans": ["搭档，合作伙伴"]},
    {"name": "impatient", "trans": ["不耐烦的，急躁的"]}, {"name": "think twice", "trans": ["三思而行"]},
    {"name": "do the dishes", "trans": ["洗碗"]}, {"name": "lunar", "trans": ["月球的"]},
    {"name": "calendar", "trans": ["日历，挂历"]}, {"name": "animal sign", "trans": ["生肖"]},
    {"name": "represent", "trans": ["代表，象征"]}, {"name": "appear", "trans": ["出现"]},
    {"name": "fixed", "trans": ["固定的"]}, {"name": "cycle", "trans": ["循环"]},
    {"name": "powerful", "trans": ["有力的，强大的"]}, {"name": "lively", "trans": ["活泼的，生机勃勃的"]},
    {"name": "practical", "trans": ["实际的"]}, {"name": "loyal", "trans": ["忠诚的"]},
    {"name": "in all", "trans": ["总共，总计"]}, {"name": "star sign", "trans": ["星座"]},
    {"name": "divide", "trans": ["分开，分"]}, {"name": "divide...into...", "trans": ["把……分成……"]},
    {"name": "shape", "trans": ["使成形，塑造"]}, {"name": "speech", "trans": ["演说，讲话，发言，台词"]},
    {"name": "absent", "trans": ["缺席的"]}, {"name": "monitor", "trans": ["班长"]},
    {"name": "position", "trans": ["职位，位置，名次"]}, {"name": "agree with", "trans": ["同意某人（的看法）"]},
    {"name": "indigo", "trans": ["靛蓝，靛青"]}, {"name": "violet", "trans": ["紫罗兰色"]},
    {"name": "rainbow", "trans": ["彩虹"]}, {"name": "mood", "trans": ["心情，情绪"]},
    {"name": "influence", "trans": ["影响"]}, {"name": "whether", "trans": ["是否"]},
    {"name": "characteristic", "trans": ["特征，品质"]}, {"name": "calm", "trans": ["平静的，沉着的"]},
    {"name": "relaxed", "trans": ["放松的，自在的"]}, {"name": "peace", "trans": ["安宁，和平，和睦"]},
    {"name": "sadness", "trans": ["悲哀，忧伤"]}, {"name": "purity", "trans": ["纯洁"]},
    {"name": "wedding", "trans": ["婚礼，结婚庆典"]}, {"name": "prefer", "trans": ["宁愿选择，更喜欢"]},
    {"name": "create", "trans": ["造成，引起；创造，创建"]}, {"name": "feeling", "trans": ["感觉，感受"]},
    {"name": "cheer up", "trans": ["使振作起来"]}, {"name": "remind", "trans": ["提醒，使想起"]},
    {"name": "wisdom", "trans": ["智慧"]}, {"name": "as", "trans": ["因为"]},
    {"name": "envy", "trans": ["妒忌，羡慕"]}, {"name": "green with envy", "trans": ["妒忌的，眼红的"]},
    {"name": "require", "trans": ["需要，要求"]}, {"name": "strength", "trans": ["力量"]},
    {"name": "heat", "trans": ["热"]}, {"name": "difficulty", "trans": ["困难，费力"]},
    {"name": "have difficulty in doing", "trans": ["做某事费劲"]}, {"name": "decision", "trans": ["决定"]},
    {"name": "relationship", "trans": ["关系"]}, {"name": "certainly", "trans": ["当然，必定地"]},
    {"name": "everyday", "trans": ["每天的，日常的"]}, {"name": "personal", "trans": ["个人的，私人的"]},
    {"name": "suit", "trans": ["适合"]}, {"name": "celebration", "trans": ["庆祝，庆祝活动"]},
    {"name": "ancient", "trans": ["古代的，古老的"]}, {"name": "therapy", "trans": ["疗法，治疗"]},
    {"name": "discover", "trans": ["发现，发觉"]}, {"name": "teens", "trans": ["十几岁"]},
    {"name": "promise", "trans": ["承诺，允诺"]}, {"name": "or", "trans": ["否则"]},
    {"name": "work", "trans": ["奏效，产生预期的效果"]}, {"name": "practise", "trans": ["从事，执业"]},
    {"name": "stressed", "trans": ["紧张的，有压力的"]}, {"name": "suggest", "trans": ["建议"]},
    {"name": "would rather", "trans": ["宁愿，更喜欢"]}, {"name": "trust", "trans": ["信任"]},
    {"name": "calm", "trans": ["平静，镇静"]}, {"name": "warmth", "trans": ["温暖，暖和，热情"]},
    {"name": "handbag", "trans": ["女用皮包，手提包"]}, {"name": "match", "trans": ["相配，般配"]},
    {"name": "balance", "trans": ["使……平衡"]}, {"name": "teenage", "trans": ["青少年的"]},
    {"name": "mark", "trans": ["分数"]}, {"name": "mad", "trans": ["发疯的，生气的"]},
    {"name": "drive sb mad", "trans": ["使人受不了"]}, {"name": "exam", "trans": ["考试，测试"]},
    {"name": "perhaps", "trans": ["或许，可能"]}, {"name": "deal", "trans": ["处理"]},
    {"name": "deal with", "trans": ["处理，对付"]}, {"name": "choice", "trans": ["选择"]},
    {"name": "but", "trans": ["除……外；只有"]}, {"name": "stay up", "trans": ["熬夜"]},
    {"name": "awake", "trans": ["醒着的"]}, {"name": "hardly", "trans": ["几乎不"]},
    {"name": "imagine", "trans": ["想象，设想"]}, {"name": "doubt", "trans": ["怀疑"]},
    {"name": "worth", "trans": ["值得"]}, {"name": "be worth doing", "trans": ["值得做某事"]},
    {"name": "suggestion", "trans": ["建议"]}, {"name": "cause", "trans": ["原因"]},
    {"name": "strict", "trans": ["严格的，严厉的"]}, {"name": "be strict with", "trans": ["对某人要求严格"]},
    {"name": "stay out", "trans": ["待在户外，（晚上）不回家"]}, {"name": "schoolwork", "trans": ["课业"]},
    {"name": "valuable", "trans": ["宝贵的，贵重的"]}, {"name": "friendship", "trans": ["友谊"]},
    {"name": "list", "trans": ["清单"]}, {"name": "work out", "trans": ["算出，解决"]},
    {"name": "according to", "trans": ["根据"]}, {"name": "whom", "trans": ["谁（宾格）"]},
    {"name": "silence", "trans": ["安静，寂静，沉默"]}, {"name": "worry", "trans": ["担心，令人担忧的事"]},
    {"name": "method", "trans": ["方法"]}, {"name": "solve", "trans": ["解决，解答"]},
    {"name": "dictionary", "trans": ["字典"]}, {"name": "youth worker", "trans": ["青少年辅导员"]},
    {"name": "reply", "trans": ["答复，回答"]}, {"name": "chemistry", "trans": ["化学"]},
    {"name": "laugh at", "trans": ["嘲笑"]}, {"name": "bookworm", "trans": ["书虫，书呆子"]},
    {"name": "progress", "trans": ["进展，进步"]}, {"name": "worried", "trans": ["担心的，烦恼的"]},
    {"name": "go over", "trans": ["复习，回顾"]}, {"name": "aloud", "trans": ["大声地，出声地"]},
    {"name": "pronounce", "trans": ["发音"]}, {"name": "correctly", "trans": ["正确地"]},
    {"name": "pronunciation", "trans": ["发音"]}, {"name": "mention", "trans": ["提及，说起"]},
    {"name": "don't mention it", "trans": ["不客气"]}, {"name": "pressure", "trans": ["精神压力，紧张"]},
    {"name": "be of sb's age", "trans": ["与……同龄"]}, {"name": "time", "trans": ["挂在心上；惦记"]},
    {"name": "period", "trans": ["时期，时代"]}, {"name": "whenever", "trans": ["无论如何"]},
    {"name": "through", "trans": ["以，凭借"]}, {"name": "as soon as", "trans": ["一……就"]},
    {"name": "a great deal", "trans": ["大量，许多"]}, {"name": "junior high", "trans": ["初级中学"]},
    {"name": "try out for", "trans": ["参加……选拔"]}, {"name": "lose heart", "trans": ["泄气，灰心"]},
    {"name": "score", "trans": ["得分"]}, {"name": "senior high", "trans": ["高级中学"]},
    {"name": "stand", "trans": ["看台"]}, {"name": "change one's mind", "trans": ["改变主意"]},
    {"name": "leader", "trans": ["领导者"]}, {"name": "name", "trans": ["命名"]},
    {"name": "university", "trans": ["大学"]}, {"name": "simply", "trans": ["仅仅，简直"]},
    {"name": "junior college", "trans": ["两年制专科学校"]}, {"name": "national", "trans": ["国家的"]},
    {"name": "championship", "trans": ["锦标赛，大赛"]}, {"name": "succeed", "trans": ["成功"]},
    {"name": "succeed in doing", "trans": ["成功做某事"]}, {"name": "scholarship", "trans": ["奖学金"]},
    {"name": "although", "trans": ["尽管，虽然"]}, {"name": "graduate", "trans": ["毕业"]},
    {"name": "force", "trans": ["强迫，迫使"]}, {"name": "league", "trans": ["联盟，社团"]},
    {"name": "remain", "trans": ["逗留，保持不变"]}, {"name": "notice", "trans": ["注意，察觉"]},
    {"name": "achievement", "trans": ["成就，成绩"]}, {"name": "prove", "trans": ["证明"]},
    {"name": "matter", "trans": ["要紧，有重大影响"]}, {"name": "career", "trans": ["生涯，职业"]},
    {"name": "against", "trans": ["对……抗"]}, {"name": "break out", "trans": ["爆发"]},
    {"name": "record", "trans": ["记录"]}, {"name": "symbol", "trans": ["象征"]},
    {"name": "victory", "trans": ["胜利"]}, {"name": "spirit", "trans": ["精神，灵魂"]},
    {"name": "Jew", "trans": ["犹太人"]}, {"name": "hide away", "trans": ["躲藏起来"]},
    {"name": "Nazi", "trans": ["纳粹的；纳粹分子"]}, {"name": "die of/from", "trans": ["死于"]},
    {"name": "German", "trans": ["德国人的"]}, {"name": "thought", "trans": ["想法，看法"]},
    {"name": "survive", "trans": ["幸存，生存"]}, {"name": "admire", "trans": ["钦佩，羡慕"]},
    {"name": "courage", "trans": ["勇气"]}, {"name": "in fear of one's life", "trans": ["为生命安全担忧"]},
    {"name": "unusual", "trans": ["不寻常的"]}, {"name": "cell", "trans": ["细胞"]},
    {"name": "cancer", "trans": ["癌症"]}, {"name": "surprise", "trans": ["惊奇，诧异"]},
    {"name": "to one's surprise", "trans": ["令某人惊奇的是"]}, {"name": "research", "trans": ["研究，调查"]},
    {"name": "death", "trans": ["死，死亡"]}, {"name": "present", "trans": ["礼物"]},
    {"name": "central", "trans": ["中心的"]}, {"name": "country", "trans": ["国家"]},
    {"name": "stone", "trans": ["石头"]}, {"name": "American", "trans": ["美国的；美国人"]},
    {"name": "drama", "trans": ["戏剧"]}, {"name": "last", "trans": ["上一个的，刚过去的"]},
    {"name": "fan", "trans": ["风扇；狂热爱好者"]}, {"name": "scared", "trans": ["害怕的"]},
    {"name": "prize", "trans": ["奖（品）"]}, {"name": "live", "trans": ["在现场直播，在实况直播"]},
    {"name": "comedy", "trans": ["喜剧，喜剧片"]}, {"name": "cover", "trans": ["遮盖，覆盖"]},
    {"name": "unless", "trans": ["除非，如果不"]}, {"name": "waste", "trans": ["浪费"]},
    {"name": "documentary", "trans": ["纪录片"]}, {"name": "drama series", "trans": ["系列剧"]},
    {"name": "game show", "trans": ["游戏表演，竞赛节目"]}, {"name": "real-life", "trans": ["真实生活的"]},
    {"name": "round-up", "trans": ["新闻概要，摘要"]}, {"name": "up-to-date", "trans": ["最新的，现代的"]},
    {"name": "coming", "trans": ["即将来临的"]}, {"name": "Asian", "trans": ["亚洲的"]},
    {"name": "vote", "trans": ["投票，选举"]}, {"name": "music video", "trans": ["音乐视频"]},
    {"name": "announce", "trans": ["宣布，宣告"]}, {"name": "text message", "trans": ["短信"]},
    {"name": "murder", "trans": ["谋杀"]}, {"name": "murderer", "trans": ["杀人犯，凶手"]},
    {"name": "horror", "trans": ["恐怖"]}, {"name": "direct", "trans": ["导演，指导"]},
    {"name": "director", "trans": ["导演"]}, {"name": "wealthy", "trans": ["富有的"]},
    {"name": "mystery", "trans": ["神秘，疑案故事"]}, {"name": "might", "trans": ["或许，可能"]},
    {"name": "scene", "trans": ["景象，风光，现场"]}, {"name": "latest", "trans": ["最新的，最近的"]},
    {"name": "record", "trans": ["录制，录音"]}, {"name": "attack", "trans": ["攻击，进攻"]},
    {"name": "polar bear", "trans": ["北极熊"]}, {"name": "male", "trans": ["雄性的，男性的"]},
    {"name": "studio", "trans": ["摄影棚，录音室"]}, {"name": "minibus", "trans": ["小型公共汽车"]},
    {"name": "view", "trans": ["观看"]}, {"name": "silly", "trans": ["愚蠢的"]},
    {"name": "actor", "trans": ["演员"]}, {"name": "actress", "trans": ["女演员"]},
    {"name": "dancer", "trans": ["跳舞者，舞蹈演员"]}, {"name": "kung fu", "trans": ["功夫，武术"]},
    {"name": "dinosaur", "trans": ["恐龙"]}, {"name": "role", "trans": ["作用，职能，角色"]},
    {"name": "mistake", "trans": ["错误，失误"]}, {"name": "police officer", "trans": ["警察"]},
    {"name": "guess", "trans": ["猜"]}, {"name": "medium", "trans": ["中等的"]},
    {"name": "crime", "trans": ["犯罪活动"]}, {"name": "criminal", "trans": ["罪犯"]},
    {"name": "burglary", "trans": ["入室盗窃"]}, {"name": "burglar", "trans": ["入室窃贼"]},
    {"name": "suspect", "trans": ["嫌疑犯"]}, {"name": "detective", "trans": ["侦探"]},
    {"name": "witness", "trans": ["目击者，证人"]}, {"name": "evidence", "trans": ["证据"]},
    {"name": "fingerprint", "trans": ["指纹"]}, {"name": "victim", "trans": ["受害者"]},
    {"name": "shop lifting", "trans": ["入店行窃"]}, {"name": "theft", "trans": ["盗窃"]},
]

GRADE_9_LOWER = [
    {"name": "tiring", "trans": ["使人疲劳的，累人的"]}, {"name": "step", "trans": ["台阶，梯级"]},
    {"name": "Chinese knot", "trans": ["中国结"]}, {"name": "Chinese opera", "trans": ["中国戏曲"]},
    {"name": "Chinese paper-cutting", "trans": ["中国剪纸"]}, {"name": "chopsticks", "trans": ["筷子"]},
    {"name": "dragon dance", "trans": ["舞龙"]}, {"name": "middle", "trans": ["中间，中央"]},
    {"name": "in the middle of", "trans": ["在……中间"]}, {"name": "emperor", "trans": ["皇帝"]},
    {"name": "raising", "trans": ["升高"]}, {"name": "flag", "trans": ["旗帜"]},
    {"name": "landscape", "trans": ["风景；地形"]}, {"name": "attraction", "trans": ["向往的地方；吸引"]},
    {"name": "watchtower", "trans": ["瞭望塔"]}, {"name": "wonder", "trans": ["奇迹"]},
    {"name": "lie", "trans": ["位于"]}, {"name": "shape", "trans": ["形状，外形"]},
    {"name": "underground", "trans": ["地下的"]}, {"name": "cave", "trans": ["洞穴"]},
    {"name": "hang", "trans": ["垂下；悬挂"]}, {"name": "point", "trans": ["指，指向"]},
    {"name": "upwards", "trans": ["向上"]}, {"name": "hire", "trans": ["租用；雇用"]},
    {"name": "eastern", "trans": ["东部的，东方的"]}, {"name": "south-east", "trans": ["东南方"]},
    {"name": "location", "trans": ["地点，方位"]}, {"name": "take up", "trans": ["占据（空间），占用（时间）"]},
    {"name": "quarter", "trans": ["四分之一"]}, {"name": "either", "trans": ["两者之一"]},
    {"name": "level", "trans": ["水平"]}, {"name": "service", "trans": ["服务；工作"]},
    {"name": "Japanese", "trans": ["日本（人）的"]}, {"name": "state", "trans": ["国家；州"]},
    {"name": "Hindi", "trans": ["印地语"]}, {"name": "billion", "trans": ["十亿"]},
    {"name": "population", "trans": ["人口"]}, {"name": "iron", "trans": ["铁"]},
    {"name": "IT", "trans": ["信息技术"]}, {"name": "technology", "trans": ["技术"]},
    {"name": "custom", "trans": ["风俗，习俗"]}, {"name": "fair", "trans": ["集市；庙会；展览会"]},
    {"name": "sari", "trans": ["莎丽（印度妇女民族服饰）"]}, {"name": "Indian", "trans": ["印度（人）的"]},
    {"name": "inventor", "trans": ["发明者"]}, {"name": "invent", "trans": ["发明"]},
    {"name": "explorer", "trans": ["探险者；考察者"]}, {"name": "South African", "trans": ["南非人"]},
    {"name": "fighter", "trans": ["斗士，战斗者；战斗机"]}, {"name": "invention", "trans": ["发明物；创意"]},
    {"name": "Italian", "trans": ["意大利人"]}, {"name": "European", "trans": ["欧洲人"]},
    {"name": "Russian", "trans": ["俄罗斯人"]}, {"name": "pilot", "trans": ["飞行员"]},
    {"name": "licence", "trans": ["执照，许可证"]}, {"name": "navy", "trans": ["海军"]},
    {"name": "serve", "trans": ["服役；服务，招待"]}, {"name": "test", "trans": ["测试；检验"]},
    {"name": "aircraft", "trans": ["飞机，航空器"]}, {"name": "astronaut", "trans": ["宇航员"]},
    {"name": "spacecraft", "trans": ["宇宙飞船，航天器"]}, {"name": "spin", "trans": ["快速旋转"]},
    {"name": "control", "trans": ["控制"]}, {"name": "out of control", "trans": ["失去控制，无法管理"]},
    {"name": "order", "trans": ["命令，指挥，要求"]}, {"name": "cut short", "trans": ["缩短"]},
    {"name": "Pacific", "trans": ["太平洋的"]}, {"name": "ocean", "trans": ["海洋"]},
    {"name": "land", "trans": ["（使）着陆，（使）降落"]}, {"name": "giant", "trans": ["巨大的；伟大的"]},
    {"name": "leap", "trans": ["跳跃；跃升"]}, {"name": "mankind", "trans": ["人类"]},
    {"name": "step", "trans": ["走，跨步"]}, {"name": "surface", "trans": ["表面；表层"]},
    {"name": "further", "trans": ["更多的，更进一步的"]}, {"name": "citizen", "trans": ["公民；市民"]},
    {"name": "pride", "trans": ["骄傲；可引以为豪的人（或物）"]}, {"name": "passage", "trans": ["章节，乐段"]},
    {"name": "by hand", "trans": ["手工"]}, {"name": "mathematics", "trans": ["数学"]},
    {"name": "scientist", "trans": ["科学家"]}, {"name": "radium", "trans": ["镭"]},
    {"name": "laboratory", "trans": ["实验室"]}, {"name": "professor", "trans": ["教授"]},
    {"name": "discovery", "trans": ["发现；发现物"]}, {"name": "unknown", "trans": ["未知的；不出名的"]},
    {"name": "widely", "trans": ["广泛地，普遍地"]}, {"name": "hybrid", "trans": ["杂交的"]},
    {"name": "title", "trans": ["标题；职位名称"]}, {"name": "agriculture", "trans": ["农业"]},
    {"name": "hunger", "trans": ["饥饿"]}, {"name": "happen to", "trans": ["碰巧"]},
    {"name": "advantage", "trans": ["优势，有利条件"]}, {"name": "at present", "trans": ["现在，目前"]},
    {"name": "contribution", "trans": ["贡献"]}, {"name": "increase", "trans": ["增加"]},
    {"name": "production", "trans": ["生产；产量"]}, {"name": "development", "trans": ["发展"]},
    {"name": "robot", "trans": ["机器人"]}, {"name": "post", "trans": ["邮寄"]},
    {"name": "explore", "trans": ["探索；探讨"]}, {"name": "outer space", "trans": ["太空"]},
    {"name": "brain", "trans": ["大脑"]}, {"name": "whatever", "trans": ["任何，一切事物"]},
    {"name": "order", "trans": ["订购"]}, {"name": "suit", "trans": ["套装"]},
    {"name": "smoothly", "trans": ["平整地；顺利地"]}, {"name": "iron", "trans": ["熨烫"]},
    {"name": "in general", "trans": ["大体上；总的来说"]}, {"name": "satisfy", "trans": ["满足，使满意"]},
    {"name": "need", "trans": ["需要的事物；欲望"]}, {"name": "virus", "trans": ["病毒"]},
    {"name": "no longer", "trans": ["不再"]}, {"name": "properly", "trans": ["正确地，适当地"]},
    {"name": "completely", "trans": ["完全的，彻底的"]}, {"name": "mess", "trans": ["乱七八糟"]},
    {"name": "lay", "trans": ["放，搁"]}, {"name": "store", "trans": ["储藏，存储"]},
    {"name": "coin", "trans": ["硬币"]}, {"name": "bill", "trans": ["账单"]},
    {"name": "private", "trans": ["私人的"]}, {"name": "paper", "trans": ["文件，证明"]},
    {"name": "spread", "trans": ["（使）散开；扩散"]}, {"name": "wheel", "trans": ["轮子，车轮"]},
    {"name": "pill", "trans": ["药片；药丸"]}, {"name": "unsure", "trans": ["不确定，没把握"]},
    {"name": "forgetful", "trans": ["健忘的"]}, {"name": "stair", "trans": ["楼梯"]},
    {"name": "battery", "trans": ["电池"]}, {"name": "customer", "trans": ["消费者，顾客"]},
    {"name": "hold on", "trans": ["（打电话时）等待，不挂断"]},
    {"name": "through", "trans": ["（电话）接通"]}, {"name": "put through", "trans": ["给……接通（电话）"]},
    {"name": "satisfied", "trans": ["满意的，满足的"]}, {"name": "be satisfied with", "trans": ["对……感到满意"]},
    {"name": "first of all", "trans": ["首先"]}, {"name": "quality", "trans": ["质量"]},
    {"name": "up to standard", "trans": ["达到标准"]}, {"name": "completely", "trans": ["完全地"]},
    {"name": "regret", "trans": ["后悔；遗憾"]}, {"name": "product", "trans": ["产品，成果"]},
    {"name": "Mars", "trans": ["火星"]}, {"name": "helmet", "trans": ["头盔"]},
    {"name": "air tank", "trans": ["氧气罐"]}, {"name": "dried food", "trans": ["干粮"]},
    {"name": "power pack", "trans": ["电源包"]}, {"name": "sleeping bag", "trans": ["睡袋"]},
    {"name": "gravity", "trans": ["重力"]}, {"name": "planet", "trans": ["行星"]},
    {"name": "crowded", "trans": ["拥挤的"]}, {"name": "polluted", "trans": ["被污染的"]},
    {"name": "rapid", "trans": ["快的，迅速的"]}, {"name": "increase", "trans": ["增加"]},
    {"name": "over again", "trans": ["再，重新"]}, {"name": "passenger", "trans": ["乘客"]},
    {"name": "at the speed of", "trans": ["以……的速度"]},
    {"name": "uncomfortable", "trans": ["使人不舒服的；不舒适的"]}, {"name": "oxygen", "trans": ["氧气"]},
    {"name": "in the form of", "trans": ["以……的形式"]}, {"name": "tasty", "trans": ["味道好的"]},
    {"name": "specially", "trans": ["专门地，特地"]}, {"name": "float", "trans": ["飘浮；漂浮"]},
    {"name": "compare", "trans": ["比较"]}, {"name": "compare to/with", "trans": ["与……相比"]},
    {"name": "interplanetary", "trans": ["行星间的"]}, {"name": "network", "trans": ["网络"]},
    {"name": "challenging", "trans": ["挑战性的"]}, {"name": "rapidly", "trans": ["快地，迅速地"]},
    {"name": "aware", "trans": ["知道，意识到"]}, {"name": "circle", "trans": ["围绕；将……圈起来"]},
    {"name": "agreement", "trans": ["一致，同意"]}, {"name": "distance", "trans": ["距离；远处"]},
    {"name": "possibility", "trans": ["可能性"]}, {"name": "alien", "trans": ["外星人"]},
    {"name": "stranger", "trans": ["外来者；陌生人"]}, {"name": "carry out", "trans": ["开展"]},
    {"name": "percentage", "trans": ["百分数，百分比"]}, {"name": "disadvantage", "trans": ["缺点，不利条件"]},
    {"name": "risk", "trans": ["风险"]}, {"name": "after all", "trans": ["毕竟"]},
    {"name": "goods", "trans": ["商品"]}, {"name": "electronic", "trans": ["电子的"]},
    {"name": "entertainment", "trans": ["娱乐"]},
]

if __name__ == '__main__':
    for filename, data in [
        ('YiLinCz_7_1.json', GRADE_7_UPPER),
        ('YiLinCz_7_2.json', GRADE_7_LOWER),
        ('YiLinCz_8_1.json', GRADE_8_UPPER),
        ('YiLinCz_8_2.json', GRADE_8_LOWER),
        ('YiLinCz_9_1.json', GRADE_9_UPPER),
        ('YiLinCz_9_2.json', GRADE_9_LOWER),
    ]:
        path = os.path.join(DICTS_DIR, filename)
        with open(path, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(f"Saved {len(data)} words to {filename}")
    print("Done! All 6 Yilin dictionary files generated.")
